"""P5 — order consolidation enums (foundation; no auto-MM / split shipment)."""

from __future__ import annotations

PLAN_STATUS_DRAFT = "DRAFT"
PLAN_STATUS_READY = "READY"
PLAN_STATUS_IN_PROGRESS = "IN_PROGRESS"
PLAN_STATUS_COMPLETED = "COMPLETED"
PLAN_STATUS_CANCELLED = "CANCELLED"

ORDER_CONSOLIDATION_PLAN_STATUSES = (
    PLAN_STATUS_DRAFT,
    PLAN_STATUS_READY,
    PLAN_STATUS_IN_PROGRESS,
    PLAN_STATUS_COMPLETED,
    PLAN_STATUS_CANCELLED,
)

ITEM_STATUS_WAITING = "WAITING"
ITEM_STATUS_MM_CREATED = "MM_CREATED"
ITEM_STATUS_IN_TRANSIT = "IN_TRANSIT"
ITEM_STATUS_RECEIVED = "RECEIVED"
ITEM_STATUS_CANCELLED = "CANCELLED"

ORDER_CONSOLIDATION_ITEM_STATUSES = (
    ITEM_STATUS_WAITING,
    ITEM_STATUS_MM_CREATED,
    ITEM_STATUS_IN_TRANSIT,
    ITEM_STATUS_RECEIVED,
    ITEM_STATUS_CANCELLED,
)

RESULT_CONSOLIDATION_NOT_REQUIRED = "CONSOLIDATION_NOT_REQUIRED"
RESULT_MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
RESULT_PLAN_CREATED = "PLAN_CREATED"

MM_CREATION_SOURCE_CONSOLIDATION = "CONSOLIDATION"
