"""P5 — order consolidation enums (foundation; no auto-MM / split shipment)."""

from __future__ import annotations

PLAN_STATUS_DRAFT = "DRAFT"
PLAN_STATUS_READY = "READY"
PLAN_STATUS_IN_PROGRESS = "IN_PROGRESS"
PLAN_STATUS_COMPLETED = "COMPLETED"
PLAN_STATUS_CANCELLED = "CANCELLED"
PLAN_STATUS_EXCEPTION = "EXCEPTION"
PLAN_STATUS_MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"

ORDER_CONSOLIDATION_PLAN_STATUSES = (
    PLAN_STATUS_DRAFT,
    PLAN_STATUS_READY,
    PLAN_STATUS_IN_PROGRESS,
    PLAN_STATUS_COMPLETED,
    PLAN_STATUS_CANCELLED,
    PLAN_STATUS_EXCEPTION,
    PLAN_STATUS_MANUAL_REVIEW_REQUIRED,
)

PLAN_STATUS_BLOCKS_FULFILLMENT = frozenset(
    {
        PLAN_STATUS_EXCEPTION,
        PLAN_STATUS_MANUAL_REVIEW_REQUIRED,
        PLAN_STATUS_CANCELLED,
    }
)

PLAN_STATUS_OPEN = frozenset(
    {
        PLAN_STATUS_DRAFT,
        PLAN_STATUS_READY,
        PLAN_STATUS_IN_PROGRESS,
        PLAN_STATUS_EXCEPTION,
        PLAN_STATUS_MANUAL_REVIEW_REQUIRED,
    }
)

ITEM_STATUS_WAITING = "WAITING"
ITEM_STATUS_MM_CREATED = "MM_CREATED"
ITEM_STATUS_IN_TRANSIT = "IN_TRANSIT"
ITEM_STATUS_RECEIVED = "RECEIVED"
ITEM_STATUS_CANCELLED = "CANCELLED"
ITEM_STATUS_SHORTAGE = "SHORTAGE"
ITEM_STATUS_DAMAGED = "DAMAGED"
ITEM_STATUS_LOST = "LOST"
ITEM_STATUS_BLOCKED = "BLOCKED"

ORDER_CONSOLIDATION_ITEM_STATUSES = (
    ITEM_STATUS_WAITING,
    ITEM_STATUS_MM_CREATED,
    ITEM_STATUS_IN_TRANSIT,
    ITEM_STATUS_RECEIVED,
    ITEM_STATUS_CANCELLED,
    ITEM_STATUS_SHORTAGE,
    ITEM_STATUS_DAMAGED,
    ITEM_STATUS_LOST,
    ITEM_STATUS_BLOCKED,
)

ITEM_STATUS_EXCEPTION = frozenset(
    {
        ITEM_STATUS_SHORTAGE,
        ITEM_STATUS_DAMAGED,
        ITEM_STATUS_LOST,
    }
)

ALERT_SEVERITY_INFO = "INFO"
ALERT_SEVERITY_WARNING = "WARNING"
ALERT_SEVERITY_CRITICAL = "CRITICAL"

ALERT_CODE_SHORTAGE = "SHORTAGE"
ALERT_CODE_DAMAGED_ITEM = "DAMAGED_ITEM"
ALERT_CODE_LOST_TRANSFER = "LOST_TRANSFER"
ALERT_CODE_TARGET_WAREHOUSE_CHANGED = "TARGET_WAREHOUSE_CHANGED"
ALERT_CODE_CONSOLIDATION_CANCELLED = "CONSOLIDATION_CANCELLED"
ALERT_CODE_ADDITIONAL_MM_REQUESTED = "ADDITIONAL_MM_REQUESTED"
ALERT_CODE_OPERATOR_DECISION_REQUIRED = "OPERATOR_DECISION_REQUIRED"
ALERT_CODE_LOST_ESCALATION = "LOST_ESCALATION"

RESULT_CONSOLIDATION_NOT_REQUIRED = "CONSOLIDATION_NOT_REQUIRED"
RESULT_MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
RESULT_PLAN_CREATED = "PLAN_CREATED"

MM_CREATION_SOURCE_CONSOLIDATION = "CONSOLIDATION"
