"""
Canonical complaint event_type values (string constants, DB-stored).

Use UPPER_SNAKE_CASE — stable for APIs and analytics.
"""

# Complaint-level
COMPLAINT_CREATED = "COMPLAINT_CREATED"
COMPLAINT_CLOSED = "COMPLAINT_CLOSED"  # emit when complaint reaches terminal status (optional dedicated row)
# Legacy dual-write only — prefer COMPLAINT_PROCESS_STATUS for new rows
COMPLAINT_STATUS_CHANGED = "COMPLAINT_STATUS_CHANGED"
# Normalized complaint workflow status (payload: { "status": "WERYFIKACJA" } — no from/to in DB)
COMPLAINT_PROCESS_STATUS = "COMPLAINT_PROCESS_STATUS"
COMPLAINT_AUTO_ACCEPTED_LAW = "COMPLAINT_AUTO_ACCEPTED_LAW"
COMPLAINT_DECISION_FLAGS_UPDATED = "COMPLAINT_DECISION_FLAGS_UPDATED"

# Lines (LINE_DECISION_SET = explicit decision change; LINE_UPDATED = generic line patch)
LINE_DECISION_SET = "LINE_DECISION_SET"
LINE_UPDATED = "LINE_UPDATED"
# Normalized line milestone (payload: { "status": "WAREHOUSE_RECEIVED" } — action code, deduped per line)
LINE_PROCESS_STATUS = "LINE_PROCESS_STATUS"
OPERATION_STEP_DONE = "OPERATION_STEP_DONE"
SETTLEMENT_SAVED = "SETTLEMENT_SAVED"

# Logistics / parcel lifecycle (payload: { "status": "DELIVERED", "shipment_id": n, ... })
SHIPMENT_STATUS = "SHIPMENT_STATUS"
# Legacy / non-status shipment events
SHIPMENT_CREATED = "SHIPMENT_CREATED"
SHIPMENT_CANCELLED = "SHIPMENT_CANCELLED"

# Financial
RESOLUTION_SET = "RESOLUTION_SET"
REFUND_CREATED = "REFUND_CREATED"
REPLACEMENT_ORDER_CREATED = "REPLACEMENT_ORDER_CREATED"

# Media
PHOTO_ADDED = "PHOTO_ADDED"
PHOTO_REMOVED = "PHOTO_REMOVED"

# Other
DEFECT_TAGS_UPDATED = "DEFECT_TAGS_UPDATED"
DOCUMENT_GENERATED = "DOCUMENT_GENERATED"
DOCUMENTS_REGENERATED = "DOCUMENTS_REGENERATED"
WMS_INSPECTION_SAVED = "WMS_INSPECTION_SAVED"
LEGACY_AUDIT = "LEGACY_AUDIT"
