"""Default system label catalog — seed source for system_labels."""

from __future__ import annotations

# (key, default_value, category, description)
SYSTEM_LABEL_SEED: list[tuple[str, str, str, str]] = [
    # App
    ("app.brandMark", "Sasist", "app", "Marka aplikacji"),
    ("app.title", "WMS", "app", "Tytuł aplikacji"),
    ("app.titleSaaS", "WMS SaaS", "app", "Tytuł SaaS"),
    # Navigation
    ("navigation.assortment", "Asortyment", "navigation", "Kategoria asortymentu"),
    ("navigation.products", "Produkty", "navigation", "Lista produktów"),
    ("navigation.bundles", "Zestawy", "navigation", "Zestawy produktów"),
    ("navigation.manufacturers", "Producenci", "navigation", "Producenci"),
    ("navigation.suppliers", "Dostawcy", "navigation", "Dostawcy"),
    ("navigation.purchaseOrders", "Zamówienia do dostawców", "navigation", "PO"),
    ("navigation.purchasingCategory", "Zakupy i planowanie", "navigation", "Kategoria zakupów"),
    ("navigation.purchasingDashboard", "Pulpit zakupów", "navigation", "Pulpit zakupów"),
    ("navigation.purchasingReplenishment", "Generator zakupów", "navigation", "Generator"),
    ("navigation.purchasingSupplierAnalytics", "Ocena dostawców", "navigation", "Analityka dostawców"),
    ("navigation.purchasingForecast", "Prognoza zakupów", "navigation", "Prognoza"),
    ("navigation.purchasingAutoReorder", "Auto-uzupełnianie", "navigation", "Auto-reorder"),
    ("navigation.purchasingPriceOpportunities", "Oszczędności zakupowe", "navigation", "Oszczędności"),
    ("navigation.addProduct", "Dodaj produkt", "navigation", "CTA produkt"),
    ("navigation.addBundle", "Dodaj zestaw", "navigation", "CTA zestaw"),
    ("navigation.addManufacturer", "Dodaj producenta", "navigation", "CTA producent"),
    ("navigation.addSupplier", "Dodaj dostawcę", "navigation", "CTA dostawca"),
    ("navigation.inventory", "Stan magazynowy", "navigation", "Stan"),
    ("navigation.orders", "Zamówienia", "navigation", "Zamówienia"),
    ("navigation.carts", "Wózki", "navigation", "Wózki"),
    ("navigation.warehouseCarriers", "Nośniki", "navigation", "Nośniki"),
    ("navigation.import", "Import", "navigation", "Import"),
    ("navigation.fleetPlanner", "Planer floty", "navigation", "Planer floty"),
    ("navigation.pickingWaves", "Fale kompletacji", "navigation", "Fale"),
    ("navigation.warehouseDesigner", "Projektant Magazynu", "navigation", "Designer"),
    ("navigation.barcodeManagement", "Etykiety / Kody kreskowe", "navigation", "Kody"),
    ("navigation.labelSystem", "System Etykiet", "navigation", "System etykiet"),
    ("navigation.setup", "Setup", "navigation", "Setup"),
    ("navigation.settingsCategory", "Ustawienia", "navigation", "Ustawienia"),
    ("navigation.administratorsNav", "Administratorzy", "navigation", "Administratorzy"),
    ("navigation.systemSetupNav", "Firma i konfiguracja", "navigation", "Firma"),
    ("navigation.printersNav", "Drukarki", "navigation", "Drukarki"),
    ("navigation.wmsSettings", "Ustawienia WMS", "navigation", "Ustawienia WMS"),
    ("navigation.returnPanelStatuses", "Zwroty — statusy panelu", "navigation", "Statusy zwrotów"),
    ("navigation.orderPanelStatuses", "Zamówienia — statusy panelu", "navigation", "Statusy zamówień"),
    ("navigation.shippingMethods", "Metody dostawy", "navigation", "Metody dostawy"),
    ("navigation.warehouseMaterials", "Materiały magazynowe", "navigation", "Materiały"),
    ("navigation.warehouseBdo", "BDO", "navigation", "BDO"),
    ("navigation.warehouseMaterialsCartons", "Kartony i opakowania", "navigation", "Kartony"),
    ("navigation.warehouseMaterialsPackaging", "Materiały pakowe", "navigation", "Pakowe"),
    ("navigation.complaintPanelStatuses", "Reklamacje — statusy panelu", "navigation", "Statusy reklamacji"),
    ("navigation.analysis", "Analiza", "navigation", "Analiza"),
    ("navigation.system", "System", "navigation", "Moduł System"),
    ("navigation.returns", "Zwroty", "navigation", "Zwroty"),
    ("navigation.wmsTerminal", "WMS", "navigation", "Terminal WMS"),
    ("navigation.complaints", "Reklamacje", "navigation", "Reklamacje"),
    ("navigation.locations", "Lokalizacje", "navigation", "Lokalizacje"),
    ("navigation.customersList", "Klienci", "navigation", "Klienci"),
    ("navigation.addCustomer", "Dodaj klienta", "navigation", "CTA klient"),
    ("navigation.groups.orders", "Zamówienia", "navigation", "Grupa zamówień"),
    ("navigation.groups.warehouse", "Magazyn", "navigation", "Grupa magazyn"),
    ("navigation.groups.customers", "Klienci", "navigation", "Grupa klienci"),
    ("navigation.documentsCategory", "Dokumenty", "navigation", "Dokumenty"),
    ("navigation.documentsSales", "Sprzedaż", "navigation", "Dok. sprzedaż"),
    ("navigation.documentsReturns", "Zwroty", "navigation", "Dok. zwroty"),
    ("navigation.documentsWarehouse", "Magazyn", "navigation", "Dok. magazyn"),
    ("navigation.settings.general", "Ogólne", "navigation", "Ustawienia ogólne"),
    ("navigation.settings.users", "Użytkownicy", "navigation", "Użytkownicy"),
    ("navigation.settings.integrations", "Integracje", "navigation", "Integracje"),
    ("navigation.warehouse.racks", "Regały", "navigation", "Regały"),
    ("navigation.warehouse.zones", "Strefy", "navigation", "Strefy"),
    ("navigation.warehouse.inventoryCount", "Inwentaryzacja", "navigation", "Inwentaryzacja"),
    ("navigation.wmsEntry", "Przejdź do WMS", "navigation", "CTA WMS"),
    # System module
    ("system.tab.health", "Zdrowie systemu", "system", "Zakładka zdrowia"),
    ("system.tab.dbSize", "Rozmiar bazy", "system", "Zakładka DB"),
    ("system.tab.metrics", "Metryki API", "system", "Zakładka metryk"),
    ("system.tab.errors", "Logi błędów", "system", "Zakładka błędów"),
    ("system.tab.changelog", "Changelog", "system", "Zakładka changelog"),
    ("system.tab.labels", "Słownik aplikacji", "system", "Słownik etykiet (SUPER_ADMIN)"),
    ("system.labels.title", "Słownik aplikacji", "system", "Tytuł panelu słownika"),
    ("system.labels.searchPlaceholder", "Szukaj po kluczu lub nazwie…", "system", "Placeholder wyszukiwarki"),
    ("system.labels.systemName", "Nazwa systemowa", "system", "Kolumna klucza"),
    ("system.labels.displayName", "Nazwa wyświetlana", "system", "Kolumna wartości"),
    ("system.labels.usagePreview", "Podgląd użycia", "system", "Podgląd"),
    ("system.labels.supportMode", "Tryb support", "system", "Przełącznik support"),
    ("system.labels.supportHint", "Pokazuje: Nazwa własna (system: Nazwa domyślna)", "system", "Opis support"),
    ("system.labels.save", "Zapisz", "system", "Przycisk zapisu"),
    ("system.labels.reset", "Przywróć domyślną", "system", "Reset custom"),
    ("system.labels.empty", "Brak etykiet", "system", "Empty state"),
]
