"""Map WMS SupplyFlowEvent types → ExecutionStatus transitions (CP4)."""

from __future__ import annotations

from .status import (
    EXECUTION_STATUS_DONE,
    EXECUTION_STATUS_FAILED,
    EXECUTION_STATUS_IN_PROGRESS,
    EXECUTION_STATUS_SKIPPED,
)

# Mirror events.types — local strings avoid circular import with Event Pipeline.
EVENT_UNLOAD_STARTED = "UNLOAD_STARTED"
EVENT_UNLOAD_FINISHED = "UNLOAD_FINISHED"
EVENT_PUTAWAY_STARTED = "PUTAWAY_STARTED"
EVENT_PUTAWAY_FINISHED = "PUTAWAY_FINISHED"
EVENT_EXECUTION_CANCELLED = "EXECUTION_CANCELLED"
EVENT_EXECUTION_FAILED = "EXECUTION_FAILED"

# Event → target status for matching steps.
EVENT_TO_STEP_STATUS: dict[str, str] = {
    EVENT_UNLOAD_STARTED: EXECUTION_STATUS_IN_PROGRESS,
    EVENT_UNLOAD_FINISHED: EXECUTION_STATUS_DONE,
    EVENT_PUTAWAY_STARTED: EXECUTION_STATUS_IN_PROGRESS,
    EVENT_PUTAWAY_FINISHED: EXECUTION_STATUS_DONE,
    EVENT_EXECUTION_CANCELLED: EXECUTION_STATUS_SKIPPED,
    EVENT_EXECUTION_FAILED: EXECUTION_STATUS_FAILED,
}

_UNLOAD_ACTIONS = frozenset(
    {
        "START_UNLOAD",
        "CONTINUE_UNLOAD",
        "CONTINUE_RECEIVING",
        "RECEIVE_DELIVERY",
    }
)
_PUTAWAY_ACTIONS = frozenset(
    {
        "START_PUTAWAY",
        "CONTINUE_PUTAWAY",
        "CONSIDER_CROSS_DOCK",
    }
)

EVENT_ACTION_FAMILIES: dict[str, frozenset[str]] = {
    EVENT_UNLOAD_STARTED: _UNLOAD_ACTIONS,
    EVENT_UNLOAD_FINISHED: _UNLOAD_ACTIONS,
    EVENT_PUTAWAY_STARTED: _PUTAWAY_ACTIONS,
    EVENT_PUTAWAY_FINISHED: _PUTAWAY_ACTIONS,
    EVENT_EXECUTION_CANCELLED: frozenset(),
    EVENT_EXECUTION_FAILED: frozenset(),
}

MONITOR_EVENT_TYPES: frozenset[str] = frozenset(EVENT_TO_STEP_STATUS.keys())
