"""Sasist Printer Agent — CustomTkinter theme tokens."""

PRIMARY = "#F97316"
PRIMARY_HOVER = "#EA580C"
BG = "#FFF7ED"
CARD = "#FFFFFF"
BORDER = "#FED7AA"
SUCCESS = "#22C55E"
DANGER = "#DC2626"
WARNING = "#F59E0B"
TEXT = "#1E293B"
MUTED = "#64748B"
SIDEBAR = "#FFEDD5"
PREVIEW_BG = "#FFFBF5"

CORNER_RADIUS = 12
CORNER_RADIUS_SM = 8
PAD = 16

FONT = ("Segoe UI", 13)
FONT_BOLD = ("Segoe UI", 13, "bold")
FONT_TITLE = ("Segoe UI", 18, "bold")
FONT_SECTION = ("Segoe UI", 14, "bold")
FONT_SMALL = ("Segoe UI", 11)
FONT_MONO = ("Consolas", 11)

# Legacy Tk setup wizard aliases
PADDING = PAD
CARD_PADX = PAD
CARD_PADY = PAD
FONT_FAMILY = FONT
FONT_FAMILY_BOLD = FONT_BOLD
MUTED_TEXT = MUTED
NEUTRAL_TEXT = TEXT
PRIMARY_LIGHT = BORDER
SUCCESS_LIGHT = "#DCFCE7"
DANGER_LIGHT = "#FEE2E2"
