"""P2.5 — fulfillment warehouse assignment strategies (tenant configuration)."""

from __future__ import annotations

FULFILLMENT_ASSIGNMENT_MANUAL = "MANUAL"
FULFILLMENT_ASSIGNMENT_DEFAULT_WAREHOUSE = "DEFAULT_WAREHOUSE"
FULFILLMENT_ASSIGNMENT_FULFILLMENT_PRIORITY = "FULFILLMENT_PRIORITY"
FULFILLMENT_ASSIGNMENT_AUTO_ATP_FUTURE = "AUTO_ATP_FUTURE"

FULFILLMENT_ASSIGNMENT_MODES = (
    FULFILLMENT_ASSIGNMENT_MANUAL,
    FULFILLMENT_ASSIGNMENT_DEFAULT_WAREHOUSE,
    FULFILLMENT_ASSIGNMENT_FULFILLMENT_PRIORITY,
    FULFILLMENT_ASSIGNMENT_AUTO_ATP_FUTURE,
)

DEFAULT_FULFILLMENT_ASSIGNMENT_MODE = FULFILLMENT_ASSIGNMENT_DEFAULT_WAREHOUSE
