/**
 * Warehouse Layout Generator – creates multiple racks from a template in a grid.
 * Reuses createBinsForRack and the same RackState shape as drag-and-drop placement.
 */

import type { RackState, RowContainer, LevelConfigItem, StorageType, RackType } from "../../types/warehouse";
import {
  createBinsForRack,
  getLevelConfig,
  getTotalLocations,
  volumePerBinFromTotal,
  cmToCells,
  binsToLevels,
  ROW_LABEL_ADDRESS_PATTERN,
  generateRackUuid,
} from "./warehouseUtils";

/** Template spec passed to the generator (same shape as getCatalogItemSpec result + templateId). */
export type LayoutGeneratorTemplate = {
  width_cm: number;
  depth_cm: number;
  height_cm: number;
  levels: number;
  bins_per_level: number;
  aisle_letter: string;
  color?: string;
  /** Rack footprint type (WH/STORE) to persist on generated racks. */
  rack_type?: RackType;
  naming_pattern?: string;
  addressPattern?: string;
  rowId?: string;
  sectionStartIndex?: number;
  binNamingType?: "numeric" | "alpha";
  bin_type_map?: Record<string, StorageType>;
  levelConfig?: LevelConfigItem[];
  namingStrategy?: "pattern" | "rack-index" | "custom" | "manual";
  namingOrientation?: "column-first" | "row-first";
  namingPattern?: string;
  manualLabels?: Record<string, string>;
  overrides?: Record<string, string>;
  indexPadding?: number;
  startIndex?: number;
  templateId?: string;
  level_max_load_kg?: number;
};

export type LayoutGeneratorConfig = {
  template: LayoutGeneratorTemplate;
  rows: number;
  columns: number;
  rackSpacingCm: number;
  aisleWidthCm: number;
  orientation: "horizontal" | "vertical";
  startX: number;
  startY: number;
  startRowPrefix: string;
  /** Base rack_index for first generated rack (e.g. existingRackCount + 1 when appending). */
  baseRackIndex?: number;
  /** When set, racks that would extend past these bounds are not placed (building limit). */
  maxCols?: number;
  maxRows?: number;
  /** When true, row count is computed from building depth (maxRows) instead of config.rows. */
  autoLayout?: boolean;
  /** When true, rows and columns are computed from building dimensions; startX/startY = wall gap. */
  autoFillWarehouse?: boolean;
  /** Applied to every generated row container. */
  rackDirection?: "LTR" | "RTL";
  /** First row’s bin numbering; back-to-back pair’s second row uses the opposite. */
  firstRowBinDirection?: "LTR" | "RTL";
  /** When both set, cm→cells follows building_width_m/grid_cols and depth/grid_rows (non-square cells). */
  metersPerCellX?: number;
  metersPerCellY?: number;
};

/** Physical cm along layout X or Y → cell count; legacy `cmToCells` when MPC not set. */
function cellsFromCmForLayout(
  cm: number,
  axis: "x" | "y",
  mpcX: number | undefined,
  mpcY: number | undefined
): number {
  if (mpcX != null && mpcY != null && mpcX > 0 && mpcY > 0) {
    const mpc = axis === "x" ? mpcX : mpcY;
    return Math.max(0, Math.round((cm / 100) / mpc));
  }
  return Math.max(0, cmToCells(cm));
}

function invertBinDirection(d: "LTR" | "RTL"): "LTR" | "RTL" {
  return d === "LTR" ? "RTL" : "LTR";
}

/** Paired back-to-back rows: second physical row gets opposite bin direction. */
export function binDirectionForGeneratorRow(
  groupLength: number,
  rowIndexInGroup: number,
  firstRowBinDirection: "LTR" | "RTL"
): "LTR" | "RTL" {
  return groupLength === 2 && rowIndexInGroup === 1 ? invertBinDirection(firstRowBinDirection) : firstRowBinDirection;
}

export type LayoutGeneratorResult = {
  racks: RackState[];
  row_containers?: RowContainer[];
  /** True when some racks were skipped because they would exceed maxCols/maxRows. */
  truncated?: boolean;
  /** Row letters from auto planner (e.g. ["A","B","C","D","E","F"]) for UI preview. */
  plannedRows?: string[];
  /** When layout was auto-filled, the computed row and column counts. */
  autoGenerated?: { rows: number; columns: number };
};

/** Swap x↔y and width↔height (90° layout rotation). Rack drawing orientation becomes vertical. */
function transformRackFootprintForVerticalLayout(r: RackState): RackState {
  return {
    ...r,
    x: r.y,
    y: r.x,
    width: r.height,
    height: r.width,
    orientation: "vertical",
  };
}

function transformRowSlotForVerticalLayout(s: RowContainer["slots"][number]): RowContainer["slots"][number] {
  return {
    ...s,
    x: s.y,
    y: s.x,
    w: s.h,
    h: s.w,
  };
}

/** `maxCols` / `maxRows` from building width / depth in grid cells (same as warehouse floor in cell units). */
function filterLayoutToWarehouseBounds(
  result: LayoutGeneratorResult,
  warehouseWidth: number,
  warehouseHeight: number
): LayoutGeneratorResult {
  const fits = (r: RackState) =>
    r.x >= 0 &&
    r.y >= 0 &&
    r.x + r.width <= warehouseWidth &&
    r.y + r.height <= warehouseHeight;

  const beforeCount = result.racks.length;
  const racks = result.racks.filter(fits);
  const removed = beforeCount - racks.length;
  const validSlotKeys = new Set<string>();
  for (const r of racks) {
    if (r.uuid != null && String(r.uuid) !== "") validSlotKeys.add(String(r.uuid));
    if (r.rack_index != null) validSlotKeys.add(String(r.rack_index));
    if (r.id != null) validSlotKeys.add(String(r.id));
  }

  const row_containers =
    result.row_containers
      ?.map((rc) => ({
        ...rc,
        slots: rc.slots.filter((s) => s.rackId == null || validSlotKeys.has(String(s.rackId))),
      }))
      .filter((rc) => rc.slots.length > 0) ?? [];

  const truncated = (result.truncated ?? false) || removed > 0;

  return {
    ...result,
    racks,
    row_containers,
    truncated: truncated || undefined,
  };
}

/**
 * Vertical warehouse layout = same algorithm as horizontal, then this transform on racks and row slots.
 * Does not change LTR/RTL on row containers. Bounds filtering is done separately via `filterLayoutToWarehouseBounds`.
 */
function applyVerticalTransformFromHorizontal(result: LayoutGeneratorResult): LayoutGeneratorResult {
  const racks = result.racks.map(transformRackFootprintForVerticalLayout);
  const row_containers =
    result.row_containers?.map((rc) => ({
      ...rc,
      orientation: "vertical" as const,
      slots: rc.slots.map(transformRowSlotForVerticalLayout),
    })) ?? undefined;

  return {
    ...result,
    racks,
    row_containers,
  };
}

/** Next row letter from start prefix and row index. E.g. startRowPrefix "A", row 0 → "A"; row 1 → "B". */
export function nextRowLetter(startRowPrefix: string, rowIndex: number): string {
  const base = (startRowPrefix || "A").trim().toUpperCase();
  if (base.length === 0) return String.fromCharCode(65 + (rowIndex % 26));
  const code = base.charCodeAt(0);
  if (code >= 65 && code <= 90) return String.fromCharCode(65 + ((code - 65 + rowIndex) % 26));
  return String.fromCharCode(65 + (rowIndex % 26));
}

/**
 * Plan rack row structure to fit building depth: single, then back-to-back pairs, then single.
 * Used when autoLayout is true to derive row count from building depth.
 * Returns array of "single" | "pair" (e.g. ["single","pair","pair","single"]).
 */
export function planRackRowsForBuilding(
  buildingDepthCells: number,
  rackDepthCells: number,
  aisleCells: number,
  wallGapCells: number
): ("single" | "pair")[] {
  const structure: ("single" | "pair")[] = ["single"];
  let used = wallGapCells;
  used += rackDepthCells + aisleCells; // first single + aisle
  while (used + rackDepthCells * 2 + aisleCells + rackDepthCells + wallGapCells <= buildingDepthCells) {
    structure.push("pair");
    used += rackDepthCells * 2 + aisleCells;
  }
  structure.push("single");
  return structure;
}

/**
 * Expand planned structure into total row count.
 * ["single","pair","pair","single"] → 6 (rows A–F).
 */
export function plannedStructureToRowCount(structure: ("single" | "pair")[]): number {
  return structure.reduce((n, t) => n + (t === "single" ? 1 : 2), 0);
}

/**
 * Auto-fill building with racks from dimensions: compute columns from width, rows from depth (back-to-back),
 * then call the existing generator with start at wall gap.
 */
export function generateFullWarehouseLayout(
  config: LayoutGeneratorConfig,
  buildingWidthCells: number,
  buildingDepthCells: number,
  wallGapCm = 30
): LayoutGeneratorResult {
  const {
    template,
    rackSpacingCm,
    aisleWidthCm,
    startRowPrefix,
    baseRackIndex = 1,
    metersPerCellX: mpcX,
    metersPerCellY: mpcY,
  } = config;
  const rackWidthCells = cellsFromCmForLayout(template.width_cm, "x", mpcX, mpcY);
  const rackDepthCells = cellsFromCmForLayout(template.depth_cm, "y", mpcX, mpcY);
  const rackSpacingCells = Math.max(0, cellsFromCmForLayout(rackSpacingCm, "x", mpcX, mpcY));
  const aisleCells = Math.max(0, cellsFromCmForLayout(aisleWidthCm, "y", mpcX, mpcY));

  const wallGapCellsX = Math.max(0, cellsFromCmForLayout(wallGapCm, "x", mpcX, mpcY));
  const wallGapCellsY = Math.max(0, cellsFromCmForLayout(wallGapCm, "y", mpcX, mpcY));

  const columnStep = rackWidthCells + rackSpacingCells;
  const usableWidth = buildingWidthCells - wallGapCellsX * 2;
  /** Gaps only between racks, not after the last — include +rackSpacingCells in numerator (equivalent to per-rack boundary without gap after final rack). */
  const columns = Math.max(0, Math.floor((usableWidth + rackSpacingCells) / columnStep));

  const structure = planRackRowsForBuilding(
    buildingDepthCells,
    rackDepthCells,
    aisleCells,
    wallGapCellsY
  );
  const rows = plannedStructureToRowCount(structure);

  const result = generateWarehouseLayout({
    ...config,
    rows,
    columns,
    startX: wallGapCellsX,
    startY: wallGapCellsY,
    maxCols: buildingWidthCells,
    maxRows: buildingDepthCells,
    baseRackIndex,
    autoFillWarehouse: false,
  });

  return {
    ...result,
    autoGenerated: { rows, columns },
  };
}

/**
 * Group row indices for back-to-back layout: single, pair, pair, ..., single.
 * - First row (0): single.
 * - Last row (rows-1): single.
 * - All middle rows: consecutive pairs [1,2], [3,4], ...
 * Example: rows=6 → [[0], [1,2], [3,4], [5]]
 */
export function getBackToBackGroups(rows: number): number[][] {
  if (rows <= 0) return [];
  if (rows === 1) return [[0]];
  const groups: number[][] = [[0]];
  for (let i = 1; i < rows - 1; i += 2) {
    if (i + 1 < rows) groups.push([i, i + 1]);
    else groups.push([i]);
  }
  if (rows > 1) groups.push([rows - 1]);
  return groups;
}

/** Check if two axis-aligned rectangles overlap (in cell coordinates). */
export function rectanglesOverlap(
  a: { x: number; y: number; width: number; height: number },
  b: { x: number; y: number; width: number; height: number }
): boolean {
  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;
}

/** Check if any of the given racks overlap with any rack in existingRacks. */
export function hasOverlapWithRacks(
  newRacks: { x: number; y: number; width: number; height: number }[],
  existingRacks: { x: number; y: number; width: number; height: number }[]
): boolean {
  for (const a of newRacks) {
    for (const b of existingRacks) {
      if (rectanglesOverlap(a, b)) return true;
    }
  }
  return false;
}

/**
 * Build a single RackState from a template spec at the given position.
 * Reuses createBinsForRack; sets name, rowPrefix, indexInRow.
 */
export function buildRackFromTemplate(
  template: LayoutGeneratorTemplate,
  x: number,
  y: number,
  rackIndex: number,
  rackLabel: string,
  rowPrefix: string,
  indexInRow: number,
  orientation: "horizontal" | "vertical",
  /** When 180, back-to-back: rack faces opposite aisle (second row in a pair). */
  rotationDegrees?: 0 | 90 | 180,
  /** When set, grid footprint uses these cell counts (building-based grid); else legacy cm→cells. */
  footprintCells?: { widthCells: number; heightCells: number }
): RackState {
  const lc = getLevelConfig(template);
  const totalBins = getTotalLocations(lc);
  const volPerBin =
    totalBins > 0
      ? volumePerBinFromTotal(template.width_cm, template.depth_cm, template.height_cm, totalBins)
      : 0;

  const bins = createBinsForRack(
    template.aisle_letter,
    rackIndex,
    template.levels,
    template.bins_per_level,
    volPerBin,
    "M1",
    template.naming_pattern,
    template.width_cm,
    template.depth_cm,
    template.height_cm,
    template.bin_type_map,
    template.addressPattern ?? ROW_LABEL_ADDRESS_PATTERN,
    rackLabel,
    template.sectionStartIndex ?? 1,
    template.binNamingType ?? "numeric",
    lc,
    template.namingStrategy,
    template.namingOrientation,
    template.namingPattern ?? template.addressPattern,
    template.manualLabels,
    template.overrides,
    template.indexPadding,
    template.startIndex
  );

  const rackW = footprintCells?.widthCells ?? cmToCells(template.width_cm);
  const rackH = footprintCells?.heightCells ?? cmToCells(template.depth_cm);
  const width = orientation === "horizontal" ? rackW : rackH;
  const height = orientation === "horizontal" ? rackH : rackW;

  return {
    uuid: generateRackUuid(),
    x,
    y,
    width,
    height,
    orientation: orientation === "horizontal" ? "horizontal" : "vertical",
    levels: template.levels,
    bins_per_level: template.bins_per_level,
    levelConfig: lc,
    length_cm: template.depth_cm,
    width_cm: template.width_cm,
    height_cm: template.height_cm,
    aisle_letter: template.aisle_letter,
    rack_index: rackIndex,
    bins,
    rackLevels: binsToLevels(bins),
    color: template.color ?? "#3b82f6",
    rack_type: template.rack_type ?? "warehouse",
    name: rackLabel,
    rowPrefix,
    indexInRow,
    addressPattern: template.addressPattern,
    sectionStartIndex: template.sectionStartIndex,
    binNamingType: template.binNamingType,
    templateId: template.templateId,
    ...(template.level_max_load_kg != null ? { level_max_load_kg: template.level_max_load_kg } : {}),
    ...(rotationDegrees != null ? { rotationDegrees } : {}),
  } as RackState;
}

/**
 * Horizontal-only grid: rows increase Y, columns increase X. Same as legacy horizontal generator.
 * `orientation` in config is ignored; all racks use horizontal footprint on the grid.
 * 1 grid cell = 10 cm (cmToCells).
 */
export function generateHorizontalLayout(config: LayoutGeneratorConfig): LayoutGeneratorResult {
  const {
    template,
    rows: configRows,
    columns,
    rackSpacingCm,
    aisleWidthCm,
    startX,
    startY,
    startRowPrefix,
    baseRackIndex = 1,
    maxCols,
    maxRows,
    autoLayout = false,
    rackDirection = "LTR",
    firstRowBinDirection = "LTR",
    metersPerCellX: mpcX,
    metersPerCellY: mpcY,
  } = config;

  const rackW = cellsFromCmForLayout(template.width_cm, "x", mpcX, mpcY);
  const rackH = cellsFromCmForLayout(template.depth_cm, "y", mpcX, mpcY);
  const spacingCells = Math.max(0, cellsFromCmForLayout(rackSpacingCm, "x", mpcX, mpcY));
  const aisleCells = Math.max(0, cellsFromCmForLayout(aisleWidthCm, "y", mpcX, mpcY));
  const orientedRackWidth = rackW;
  const orientedRackHeight = rackH;

  /** Building width / depth in grid cells (from `building_width_m` / depth when caller passes limits). */
  const warehouseWidth = maxCols;
  const warehouseHeight = maxRows;
  const enforceBounds =
    warehouseWidth != null &&
    warehouseHeight != null &&
    warehouseWidth > 0 &&
    warehouseHeight > 0;

  let rows = configRows;
  let plannedRows: string[] | undefined;

  if (autoLayout && maxRows != null && maxRows > 0) {
    const buildingDepthCells = maxRows;
    const rackDepthCells = rackH;
    const wallGapCellsY = Math.max(0, cellsFromCmForLayout(30, "y", mpcX, mpcY));
    const plannedStructure = planRackRowsForBuilding(
      buildingDepthCells,
      rackDepthCells,
      aisleCells,
      wallGapCellsY
    );
    rows = plannedStructureToRowCount(plannedStructure);
    plannedRows = Array.from({ length: rows }, (_, i) => nextRowLetter(startRowPrefix, i));
  }

  const racks: RackState[] = [];
  const rowContainers: RowContainer[] = [];
  let truncated = false;

  const groups = getBackToBackGroups(rows);

  // Rows increase Y. Running currentY: within a pair only rack depth; after each group add aisle.
  const stepW = orientedRackWidth + spacingCells;
  let rackIdx = baseRackIndex;
  let rowCounter = 0;
  let currentY = startY;
  for (let g = 0; g < groups.length; g++) {
    const group = groups[g]!;
    for (let ri = 0; ri < group.length; ri++) {
      const y = currentY;
      currentY += orientedRackHeight;
      if (enforceBounds && (y < 0 || y + orientedRackHeight > warehouseHeight!)) {
        truncated = true;
        break;
      }
      if (!enforceBounds && maxRows != null && y + orientedRackHeight > maxRows) {
        truncated = true;
        break;
      }
      const rowPrefix = nextRowLetter(startRowPrefix, rowCounter++);
      const slots: RowContainer["slots"] = [];
      const rotated = ri === 1; // second row in pair faces opposite aisle (180°)
      for (let c = 0; c < columns; c++) {
        const x = startX + c * stepW;
        if (enforceBounds && (x < 0 || x + orientedRackWidth > warehouseWidth!)) {
          truncated = true;
          break;
        }
        if (!enforceBounds && maxCols != null && x + orientedRackWidth > maxCols) {
          truncated = true;
          break;
        }
        const rackIndex = rackIdx++;
        const rackLabel = `${rowPrefix}${c + 1}`;
          const rack = buildRackFromTemplate(
            template,
            x,
            y,
            rackIndex,
            rackLabel,
            rowPrefix,
            c + 1,
            "horizontal",
            rotated ? 180 : undefined,
            { widthCells: orientedRackWidth, heightCells: orientedRackHeight }
          );
        racks.push(rack);
        slots.push({ x, y, w: orientedRackWidth, h: orientedRackHeight, rackId: rack.uuid });
      }
      if (slots.length > 0) {
        rowContainers.push({
          id: `row-gen-${rowCounter - 1}-${Date.now()}`,
          rowPrefix,
          orientation: "horizontal",
          rack_direction: rackDirection,
          bin_direction: binDirectionForGeneratorRow(group.length, ri, firstRowBinDirection),
          slots,
        });
      }
    }
    currentY += aisleCells; // aisle after each group (single or pair)
  }

  let result: LayoutGeneratorResult = {
    racks,
    row_containers: rowContainers,
    truncated: truncated || undefined,
    ...(plannedRows != null ? { plannedRows } : {}),
  };
  if (enforceBounds) {
    result = filterLayoutToWarehouseBounds(result, warehouseWidth!, warehouseHeight!);
  }
  return result;
}

/**
 * Generate a grid of racks from a template.
 * Vertical layout is always `generateHorizontalLayout` followed by a coordinate swap (x↔y, w↔h).
 */
export function generateWarehouseLayout(config: LayoutGeneratorConfig): LayoutGeneratorResult {
  const { orientation, maxCols, maxRows, autoFillWarehouse } = config;

  if (autoFillWarehouse && maxCols != null && maxRows != null && maxCols > 0 && maxRows > 0) {
    return generateFullWarehouseLayout(config, maxCols, maxRows);
  }

  const warehouseWidth = maxCols;
  const warehouseHeight = maxRows;
  const hasBounds =
    warehouseWidth != null && warehouseHeight != null && warehouseWidth > 0 && warehouseHeight > 0;

  let result = generateHorizontalLayout(config);
  if (orientation === "vertical") {
    result = applyVerticalTransformFromHorizontal(result);
  }
  if (hasBounds) {
    result = filterLayoutToWarehouseBounds(result, warehouseWidth!, warehouseHeight!);
  }
  return result;
}

/** Preview labels only (no real racks). Returns 2D array of rack labels. */
export function getPreviewLabels(
  rows: number,
  columns: number,
  startRowPrefix: string
): string[][] {
  const grid: string[][] = [];
  for (let r = 0; r < rows; r++) {
    const rowPrefix = nextRowLetter(startRowPrefix, r);
    const row: string[] = [];
    for (let c = 0; c < columns; c++) row.push(`${rowPrefix}${c + 1}`);
    grid.push(row);
  }
  return grid;
}
