/**
 * Warehouse Layout Generator – creates multiple racks from a template in a grid.
 * Reuses createBinsForRack and the same RackState shape as drag-and-drop placement.
 */

import type { RackState, RowContainer, LevelConfigItem } from "../../types/warehouse";
import {
  createBinsForRack,
  getLevelConfig,
  getTotalLocations,
  volumePerBinFromTotal,
  cmToCells,
  binsToLevels,
  ROW_LABEL_ADDRESS_PATTERN,
} from "./warehouseUtils";

/** Template spec passed to the generator (same shape as getCatalogItemSpec result + templateId). */
export type LayoutGeneratorTemplate = {
  width_cm: number;
  depth_cm: number;
  height_cm: number;
  levels: number;
  bins_per_level: number;
  aisle_letter: string;
  color?: string;
  naming_pattern?: string;
  addressPattern?: string;
  rowId?: string;
  sectionStartIndex?: number;
  binNamingType?: "numeric" | "alpha";
  reserve_bin_keys?: string[];
  levelConfig?: LevelConfigItem[];
  namingStrategy?: "pattern" | "rack-index" | "custom" | "manual";
  namingOrientation?: "column-first" | "row-first";
  namingPattern?: string;
  manualLabels?: Record<string, string>;
  overrides?: Record<string, string>;
  indexPadding?: number;
  startIndex?: number;
  templateId?: string;
  level_max_load_kg?: number;
};

export type LayoutGeneratorConfig = {
  template: LayoutGeneratorTemplate;
  rows: number;
  columns: number;
  rackSpacingCm: number;
  aisleWidthCm: number;
  orientation: "horizontal" | "vertical";
  startX: number;
  startY: number;
  startRowPrefix: string;
  /** Base rack_index for first generated rack (e.g. existingRackCount + 1 when appending). */
  baseRackIndex?: number;
  /** When set, racks that would extend past these bounds are not placed (building limit). */
  maxCols?: number;
  maxRows?: number;
  /** When true, row count is computed from building depth (maxRows) instead of config.rows. */
  autoLayout?: boolean;
  /** When true, rows and columns are computed from building dimensions; startX/startY = wall gap. */
  autoFillWarehouse?: boolean;
};

export type LayoutGeneratorResult = {
  racks: RackState[];
  row_containers?: RowContainer[];
  /** True when some racks were skipped because they would exceed maxCols/maxRows. */
  truncated?: boolean;
  /** Row letters from auto planner (e.g. ["A","B","C","D","E","F"]) for UI preview. */
  plannedRows?: string[];
  /** When layout was auto-filled, the computed row and column counts. */
  autoGenerated?: { rows: number; columns: number };
};

/** Next row letter from start prefix and row index. E.g. startRowPrefix "A", row 0 → "A"; row 1 → "B". */
export function nextRowLetter(startRowPrefix: string, rowIndex: number): string {
  const base = (startRowPrefix || "A").trim().toUpperCase();
  if (base.length === 0) return String.fromCharCode(65 + (rowIndex % 26));
  const code = base.charCodeAt(0);
  if (code >= 65 && code <= 90) return String.fromCharCode(65 + ((code - 65 + rowIndex) % 26));
  return String.fromCharCode(65 + (rowIndex % 26));
}

/**
 * Plan rack row structure to fit building depth: single, then back-to-back pairs, then single.
 * Used when autoLayout is true to derive row count from building depth.
 * Returns array of "single" | "pair" (e.g. ["single","pair","pair","single"]).
 */
export function planRackRowsForBuilding(
  buildingDepthCells: number,
  rackDepthCells: number,
  aisleCells: number,
  wallGapCells: number
): ("single" | "pair")[] {
  const structure: ("single" | "pair")[] = ["single"];
  let used = wallGapCells;
  used += rackDepthCells + aisleCells; // first single + aisle
  while (used + rackDepthCells * 2 + aisleCells + rackDepthCells + wallGapCells <= buildingDepthCells) {
    structure.push("pair");
    used += rackDepthCells * 2 + aisleCells;
  }
  structure.push("single");
  return structure;
}

/**
 * Expand planned structure into total row count.
 * ["single","pair","pair","single"] → 6 (rows A–F).
 */
export function plannedStructureToRowCount(structure: ("single" | "pair")[]): number {
  return structure.reduce((n, t) => n + (t === "single" ? 1 : 2), 0);
}

/**
 * Auto-fill building with racks from dimensions: compute columns from width, rows from depth (back-to-back),
 * then call the existing generator with start at wall gap.
 */
export function generateFullWarehouseLayout(
  config: LayoutGeneratorConfig,
  buildingWidthCells: number,
  buildingDepthCells: number,
  wallGapCells: number
): LayoutGeneratorResult {
  const { template, rackSpacingCm, aisleWidthCm, orientation, startRowPrefix, baseRackIndex = 1 } = config;
  const rackWidthCells = cmToCells(template.width_cm);
  const rackDepthCells = cmToCells(template.depth_cm);
  const rackSpacingCells = Math.max(0, cmToCells(rackSpacingCm));
  const aisleCells = Math.max(0, cmToCells(aisleWidthCm));

  const columnStep = rackWidthCells + rackSpacingCells;
  const usableWidth = buildingWidthCells - wallGapCells * 2;
  const columns = Math.max(0, Math.floor(usableWidth / columnStep));

  const structure = planRackRowsForBuilding(
    buildingDepthCells,
    rackDepthCells,
    aisleCells,
    wallGapCells
  );
  const rows = plannedStructureToRowCount(structure);

  const result = generateWarehouseLayout({
    ...config,
    rows,
    columns,
    startX: wallGapCells,
    startY: wallGapCells,
    maxCols: buildingWidthCells,
    maxRows: buildingDepthCells,
    baseRackIndex,
    autoFillWarehouse: false,
  });

  return {
    ...result,
    autoGenerated: { rows, columns },
  };
}

/**
 * Group row indices for back-to-back layout: single, pair, pair, ..., single.
 * - First row (0): single.
 * - Last row (rows-1): single.
 * - All middle rows: consecutive pairs [1,2], [3,4], ...
 * Example: rows=6 → [[0], [1,2], [3,4], [5]]
 */
export function getBackToBackGroups(rows: number): number[][] {
  if (rows <= 0) return [];
  if (rows === 1) return [[0]];
  const groups: number[][] = [[0]];
  for (let i = 1; i < rows - 1; i += 2) {
    if (i + 1 < rows) groups.push([i, i + 1]);
    else groups.push([i]);
  }
  if (rows > 1) groups.push([rows - 1]);
  return groups;
}

/** Check if two axis-aligned rectangles overlap (in cell coordinates). */
export function rectanglesOverlap(
  a: { x: number; y: number; width: number; height: number },
  b: { x: number; y: number; width: number; height: number }
): boolean {
  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;
}

/** Check if any of the given racks overlap with any rack in existingRacks. */
export function hasOverlapWithRacks(
  newRacks: { x: number; y: number; width: number; height: number }[],
  existingRacks: { x: number; y: number; width: number; height: number }[]
): boolean {
  for (const a of newRacks) {
    for (const b of existingRacks) {
      if (rectanglesOverlap(a, b)) return true;
    }
  }
  return false;
}

/**
 * Build a single RackState from a template spec at the given position.
 * Reuses createBinsForRack; sets name, rowPrefix, indexInRow.
 */
export function buildRackFromTemplate(
  template: LayoutGeneratorTemplate,
  x: number,
  y: number,
  rackIndex: number,
  rackLabel: string,
  rowPrefix: string,
  indexInRow: number,
  orientation: "horizontal" | "vertical",
  /** When 180, back-to-back: rack faces opposite aisle (second row in a pair). */
  rotationDegrees?: 0 | 90 | 180
): RackState {
  const lc = getLevelConfig(template);
  const totalBins = getTotalLocations(lc);
  const volPerBin =
    totalBins > 0
      ? volumePerBinFromTotal(template.width_cm, template.depth_cm, template.height_cm, totalBins)
      : 0;

  const bins = createBinsForRack(
    template.aisle_letter,
    rackIndex,
    template.levels,
    template.bins_per_level,
    volPerBin,
    "M1",
    template.naming_pattern,
    template.width_cm,
    template.depth_cm,
    template.height_cm,
    template.reserve_bin_keys,
    template.addressPattern ?? ROW_LABEL_ADDRESS_PATTERN,
    rackLabel,
    template.sectionStartIndex ?? 1,
    template.binNamingType ?? "numeric",
    lc,
    template.namingStrategy,
    template.namingOrientation,
    template.namingPattern ?? template.addressPattern,
    template.manualLabels,
    template.overrides,
    template.indexPadding,
    template.startIndex
  );

  const rackW = cmToCells(template.width_cm);
  const rackH = cmToCells(template.depth_cm);
  const width = orientation === "horizontal" ? rackW : rackH;
  const height = orientation === "horizontal" ? rackH : rackW;

  return {
    x,
    y,
    width,
    height,
    orientation: orientation === "horizontal" ? "horizontal" : "vertical",
    levels: template.levels,
    bins_per_level: template.bins_per_level,
    levelConfig: lc,
    length_cm: template.depth_cm,
    width_cm: template.width_cm,
    height_cm: template.height_cm,
    aisle_letter: template.aisle_letter,
    rack_index: rackIndex,
    bins,
    rackLevels: binsToLevels(bins),
    color: template.color ?? "#3b82f6",
    name: rackLabel,
    rowPrefix,
    indexInRow,
    addressPattern: template.addressPattern,
    sectionStartIndex: template.sectionStartIndex,
    binNamingType: template.binNamingType,
    templateId: template.templateId,
    ...(template.level_max_load_kg != null ? { level_max_load_kg: template.level_max_load_kg } : {}),
    ...(rotationDegrees != null ? { rotationDegrees } : {}),
  } as RackState;
}

/**
 * Generate a grid of racks from a template.
 * Horizontal: rows increase Y, columns increase X.
 * Vertical: rows increase X, columns increase Y.
 * 1 grid cell = 10 cm (cmToCells).
 */
export function generateWarehouseLayout(config: LayoutGeneratorConfig): LayoutGeneratorResult {
  const {
    template,
    rows: configRows,
    columns,
    rackSpacingCm,
    aisleWidthCm,
    orientation,
    startX,
    startY,
    startRowPrefix,
    baseRackIndex = 1,
    maxCols,
    maxRows,
    autoLayout = false,
    autoFillWarehouse = false,
  } = config;

  if (autoFillWarehouse && maxCols != null && maxRows != null && maxCols > 0 && maxRows > 0) {
    const wallGapCells = Math.max(0, cmToCells(30));
    return generateFullWarehouseLayout(config, maxCols, maxRows, wallGapCells);
  }

  const rackW = cmToCells(template.width_cm);
  const rackH = cmToCells(template.depth_cm);
  const spacingCells = Math.max(0, cmToCells(rackSpacingCm));
  const aisleCells = Math.max(0, cmToCells(aisleWidthCm));

  let rows = configRows;
  let plannedRows: string[] | undefined;

  if (autoLayout && maxRows != null && maxRows > 0) {
    const buildingDepthCells = maxRows;
    const rackDepthCells = rackH;
    const wallGapCells = Math.max(0, cmToCells(30));
    const plannedStructure = planRackRowsForBuilding(
      buildingDepthCells,
      rackDepthCells,
      aisleCells,
      wallGapCells
    );
    rows = plannedStructureToRowCount(plannedStructure);
    plannedRows = Array.from({ length: rows }, (_, i) => nextRowLetter(startRowPrefix, i));
  }

  const racks: RackState[] = [];
  const rowContainers: RowContainer[] = [];
  let truncated = false;

  const groups = getBackToBackGroups(rows);

  if (orientation === "horizontal") {
    // Rows increase Y. Running currentY: within a pair only rack depth; after each group add aisle.
    const stepW = rackW + spacingCells;
    let rackIdx = baseRackIndex;
    let rowCounter = 0;
    let currentY = startY;
    for (let g = 0; g < groups.length; g++) {
      const group = groups[g]!;
      for (let ri = 0; ri < group.length; ri++) {
        const y = currentY;
        currentY += rackH;
        if (maxRows != null && y + rackH > maxRows) {
          truncated = true;
          break;
        }
        const rowPrefix = nextRowLetter(startRowPrefix, rowCounter++);
        const slots: RowContainer["slots"] = [];
        const rotated = ri === 1; // second row in pair faces opposite aisle (180°)
        for (let c = 0; c < columns; c++) {
          const x = startX + c * stepW;
          if (maxCols != null && x + rackW > maxCols) {
            truncated = true;
            break;
          }
          const rackIndex = rackIdx++;
          const rackLabel = `${rowPrefix}${c + 1}`;
          const rack = buildRackFromTemplate(
            template,
            x,
            y,
            rackIndex,
            rackLabel,
            rowPrefix,
            c + 1,
            "horizontal",
            rotated ? 180 : undefined
          );
          racks.push(rack);
          slots.push({ x, y, w: rackW, h: rackH, rackId: rackIndex });
        }
        if (slots.length > 0) {
          rowContainers.push({
            id: `row-gen-${rowCounter - 1}-${Date.now()}`,
            rowPrefix,
            orientation: "horizontal",
            slots,
          });
        }
      }
      currentY += aisleCells; // aisle after each group (single or pair)
    }
  } else {
    // Rows increase X. Running currentX: same X for rows in a pair; after each group add aisle.
    const stepInRow = rackH + spacingCells;
    const stepBetweenRows = rackW + aisleCells;
    let rackIdx = baseRackIndex;
    let rowCounter = 0;
    let currentX = startX;
    for (let g = 0; g < groups.length; g++) {
      const group = groups[g]!;
      const x = currentX;
      if (maxCols != null && x + rackW > maxCols) {
        truncated = true;
        break;
      }
      for (let ri = 0; ri < group.length; ri++) {
        const rowPrefix = nextRowLetter(startRowPrefix, rowCounter++);
        const slots: RowContainer["slots"] = [];
        const rotated = ri === 1;
        const rowOffsetY = ri * columns * stepInRow;
        for (let c = 0; c < columns; c++) {
          const y = startY + rowOffsetY + c * stepInRow;
          if (maxRows != null && y + rackH > maxRows) {
            truncated = true;
            break;
          }
          const rackIndex = rackIdx++;
          const rackLabel = `${rowPrefix}${c + 1}`;
          const rack = buildRackFromTemplate(
            template,
            x,
            y,
            rackIndex,
            rackLabel,
            rowPrefix,
            c + 1,
            "vertical",
            rotated ? 180 : undefined
          );
          racks.push(rack);
          slots.push({ x, y, w: rackW, h: rackH, rackId: rackIndex });
        }
        if (slots.length > 0) {
          rowContainers.push({
            id: `row-gen-${rowCounter - 1}-${Date.now()}`,
            rowPrefix,
            orientation: "vertical",
            slots,
          });
        }
      }
      currentX += stepBetweenRows; // aisle after each group
    }
  }

  return {
    racks,
    row_containers: rowContainers,
    truncated: truncated || undefined,
    ...(plannedRows != null ? { plannedRows } : {}),
  };
}

/** Preview labels only (no real racks). Returns 2D array of rack labels. */
export function getPreviewLabels(
  rows: number,
  columns: number,
  startRowPrefix: string
): string[][] {
  const grid: string[][] = [];
  for (let r = 0; r < rows; r++) {
    const rowPrefix = nextRowLetter(startRowPrefix, r);
    const row: string[] = [];
    for (let c = 0; c < columns; c++) row.push(`${rowPrefix}${c + 1}`);
    grid.push(row);
  }
  return grid;
}
