"""Domain activity event codes — returns + production milestones."""

from __future__ import annotations

# Returns
RETURN_CREATED = "RETURN_CREATED"
RETURN_STATUS_CHANGED = "RETURN_STATUS_CHANGED"
RETURN_ITEM_ADDED = "RETURN_ITEM_ADDED"
RETURN_LINE_DECISION = "RETURN_LINE_DECISION"
RETURN_STOCK_INTAKE_SELECTED = "RETURN_STOCK_INTAKE_SELECTED"
RETURN_COMPONENT_RECOVERY = "RETURN_COMPONENT_RECOVERY"
RETURN_COMPONENT_SCRAP = "RETURN_COMPONENT_SCRAP"
RETURN_RECEIPT_CREATED = "RETURN_RECEIPT_CREATED"
RETURN_PUTAWAY_COMPLETED = "RETURN_PUTAWAY_COMPLETED"
RETURN_REFUND_COMPLETED = "RETURN_REFUND_COMPLETED"
RETURN_FINALIZED = "RETURN_FINALIZED"
RETURN_ARCHIVED = "RETURN_ARCHIVED"

# Production milestones (do not duplicate existing PRODUCTION_ORDER_* order-activity codes)
PRODUCTION_ORDER_CREATED = "PRODUCTION_ORDER_CREATED"
PRODUCTION_BATCH_CREATED = "PRODUCTION_BATCH_CREATED"
PRODUCTION_CREATED_FROM_PLANNING = "PRODUCTION_CREATED_FROM_PLANNING"
PRODUCTION_OPERATOR_ASSIGNED = "PRODUCTION_OPERATOR_ASSIGNED"
PRODUCTION_OPERATOR_CHANGED = "PRODUCTION_OPERATOR_CHANGED"
PRODUCTION_DUE_DATE_CHANGED = "PRODUCTION_DUE_DATE_CHANGED"
PRODUCTION_PLANNED_QTY_CHANGED = "PRODUCTION_PLANNED_QTY_CHANGED"
PRODUCTION_RELEASED = "PRODUCTION_RELEASED"
PRODUCTION_COMPONENT_SHORTAGE = "PRODUCTION_COMPONENT_SHORTAGE"
PRODUCTION_SHORTAGE_RESOLVED = "PRODUCTION_SHORTAGE_RESOLVED"
PRODUCTION_MATERIALS_RESERVED = "PRODUCTION_MATERIALS_RESERVED"
PRODUCTION_MATERIAL_RESERVATIONS_RELEASED = "PRODUCTION_MATERIAL_RESERVATIONS_RELEASED"
PRODUCTION_COLLECTION_STARTED = "PRODUCTION_COLLECTION_STARTED"
PRODUCTION_COLLECTION_PROGRESS = "PRODUCTION_COLLECTION_PROGRESS"
PRODUCTION_COLLECTION_COMPLETED = "PRODUCTION_COLLECTION_COMPLETED"
PRODUCTION_RW_CREATED = "PRODUCTION_RW_CREATED"
PRODUCTION_STARTED = "PRODUCTION_STARTED"
PRODUCTION_PROGRESS_REPORTED = "PRODUCTION_PROGRESS_REPORTED"  # legacy; prefer OUTPUT_REGISTERED
PRODUCTION_OUTPUT_REGISTERED = "PRODUCTION_OUTPUT_REGISTERED"
PRODUCTION_PW_CREATED = "PRODUCTION_PW_CREATED"
PRODUCTION_SENT_TO_PUTAWAY = "PRODUCTION_SENT_TO_PUTAWAY"
PRODUCTION_PUTAWAY_COMPLETED = "PRODUCTION_PUTAWAY_COMPLETED"
PRODUCTION_ORDER_DEMAND_FULFILLED = "PRODUCTION_ORDER_DEMAND_FULFILLED"
PRODUCTION_EXTERNAL_STOCK_COVERED_ORDER = "PRODUCTION_EXTERNAL_STOCK_COVERED_ORDER"
PRODUCTION_DEMAND_REDUCED = "PRODUCTION_DEMAND_REDUCED"
PRODUCTION_SOURCE_DETACHED = "PRODUCTION_SOURCE_DETACHED"
PRODUCTION_COMPLETED = "PRODUCTION_COMPLETED"
PRODUCTION_CANCELLED = "PRODUCTION_CANCELLED"
PRODUCTION_RESUMED = "PRODUCTION_RESUMED"
PRODUCTION_TRACEABILITY_BLOCKED = "PRODUCTION_TRACEABILITY_BLOCKED"
PRODUCTION_STATUS_AUTO_CHANGED = "PRODUCTION_STATUS_AUTO_CHANGED"
PRODUCTION_SHORTAGE_AUTO_RESUMED = "PRODUCTION_SHORTAGE_AUTO_RESUMED"

# Picking-entry readiness gate (Phase 2)
PICKING_ENTRY_GATE_READY = "PICKING_ENTRY_GATE_READY"
PICKING_ENTRY_GATE_BLOCKED = "PICKING_ENTRY_GATE_BLOCKED"
PICKING_ENTRY_MO_DEMAND = "PICKING_ENTRY_MO_DEMAND"
# Phase 3 — FG availability revalidation
PICKING_ENTRY_AVAILABILITY_DEMAND_REDUCED = "PICKING_ENTRY_AVAILABILITY_DEMAND_REDUCED"
PICKING_ENTRY_AVAILABILITY_DEMAND_CANCELLED = "PICKING_ENTRY_AVAILABILITY_DEMAND_CANCELLED"
PICKING_ENTRY_AVAILABILITY_RETURNED_TO_PICKING = "PICKING_ENTRY_AVAILABILITY_RETURNED_TO_PICKING"
PICKING_ENTRY_AVAILABILITY_SOURCE_DETACHED_STARTED_MO = (
    "PICKING_ENTRY_AVAILABILITY_SOURCE_DETACHED_STARTED_MO"
)

DOMAIN_EVENT_TITLES_PL: dict[str, str] = {
    RETURN_CREATED: "Utworzono zwrot",
    RETURN_STATUS_CHANGED: "Zmieniono status zwrotu",
    RETURN_ITEM_ADDED: "Dodano produkt do zwrotu",
    RETURN_LINE_DECISION: "Zapisano decyzję pozycji",
    RETURN_STOCK_INTAKE_SELECTED: "Sposób przyjęcia magazynowego",
    RETURN_COMPONENT_RECOVERY: "Rozliczono komponent",
    RETURN_COMPONENT_SCRAP: "Rozliczono komponent",
    RETURN_RECEIPT_CREATED: "Utworzono dokument Z-PZ",
    RETURN_PUTAWAY_COMPLETED: "Rozlokowano przyjęcie zwrotu",
    RETURN_REFUND_COMPLETED: "Rozliczono zwrot",
    RETURN_FINALIZED: "Zakończono zwrot",
    RETURN_ARCHIVED: "Zarchiwizowano zwrot",
    PRODUCTION_ORDER_CREATED: "Utworzono zlecenie produkcji",
    PRODUCTION_BATCH_CREATED: "Utworzono serię produkcyjną",
    PRODUCTION_CREATED_FROM_PLANNING: "Utworzono zlecenie z planowania zapasu",
    PRODUCTION_OPERATOR_ASSIGNED: "Przypisano operatora",
    PRODUCTION_OPERATOR_CHANGED: "Zmieniono operatora",
    PRODUCTION_DUE_DATE_CHANGED: "Zmieniono termin produkcji",
    PRODUCTION_PLANNED_QTY_CHANGED: "Zmieniono planowaną ilość",
    PRODUCTION_RELEASED: "Zlecenie przekazano do realizacji",
    PRODUCTION_COMPONENT_SHORTAGE: "Brak materiałów do produkcji",
    PRODUCTION_SHORTAGE_RESOLVED: "Materiały dostępne — produkcja może być wznowiona",
    PRODUCTION_MATERIALS_RESERVED: "Zarezerwowano materiały do produkcji",
    PRODUCTION_MATERIAL_RESERVATIONS_RELEASED: "Zwolniono rezerwacje materiałów",
    PRODUCTION_COLLECTION_STARTED: "Rozpoczęto pobieranie komponentów",
    PRODUCTION_COLLECTION_PROGRESS: "Postęp pobierania komponentów",
    PRODUCTION_COLLECTION_COMPLETED: "Zakończono pobieranie komponentów",
    PRODUCTION_RW_CREATED: "Utworzono dokument RW produkcji",
    PRODUCTION_STARTED: "Rozpoczęto produkcję",
    PRODUCTION_PROGRESS_REPORTED: "Zraportowano postęp produkcji",
    PRODUCTION_OUTPUT_REGISTERED: "Zarejestrowano produkcję",
    PRODUCTION_PW_CREATED: "Utworzono dokument PW produkcji",
    PRODUCTION_SENT_TO_PUTAWAY: "Przekazano wyrób do rozlokowania",
    PRODUCTION_PUTAWAY_COMPLETED: "Rozlokowano produkt gotowy z produkcji",
    PRODUCTION_ORDER_DEMAND_FULFILLED: "Produkcja pokryła zapotrzebowanie zamówienia",
    PRODUCTION_EXTERNAL_STOCK_COVERED_ORDER: "Zamówienie pokryto istniejącym stockiem",
    PRODUCTION_DEMAND_REDUCED: "Zmniejszono zapotrzebowanie produkcyjne",
    PRODUCTION_SOURCE_DETACHED: "Zamówienie pokryto z magazynu — produkcja na wolny zapas",
    PRODUCTION_COMPLETED: "Zakończono zlecenie produkcji",
    PRODUCTION_CANCELLED: "Anulowano zlecenie produkcyjne",
    PRODUCTION_RESUMED: "Wznowiono zlecenie produkcyjne",
    PRODUCTION_TRACEABILITY_BLOCKED: "Blokada identyfikowalności produkcji",
    PRODUCTION_STATUS_AUTO_CHANGED: "Automatyczna zmiana statusu produkcji",
    PRODUCTION_SHORTAGE_AUTO_RESUMED: "Wznowiono produkcję po uzupełnieniu materiałów",
    PICKING_ENTRY_GATE_READY: "Zamówienie gotowe do zbierania",
    PICKING_ENTRY_GATE_BLOCKED: "Blokada wejścia do zbierania",
    PICKING_ENTRY_MO_DEMAND: "Zapotrzebowanie produkcyjne z gate zbierania",
    PICKING_ENTRY_AVAILABILITY_DEMAND_REDUCED: "Zmniejszono zapotrzebowanie produkcyjne",
    PICKING_ENTRY_AVAILABILITY_DEMAND_CANCELLED: "Anulowano zapotrzebowanie produkcyjne",
    PICKING_ENTRY_AVAILABILITY_RETURNED_TO_PICKING: "Przywrócono zamówienie do zbierania",
    PICKING_ENTRY_AVAILABILITY_SOURCE_DETACHED_STARTED_MO: (
        "Pokrycie z magazynu — produkcja kontynuowana jako zapas"
    ),
}

INTAKE_LABEL_PL: dict[str, str] = {
    "FG": "gotowy produkt",
    "DISASSEMBLE": "rozmontowanie",
    "MIXED": "częściowo (gotowy + rozmontowanie)",
}
