"""Canonical Order › Logi event codes (Activity Log SSOT).

Domain tables remain detail SSOT; these codes are order-facing timeline summaries only.
"""

from __future__ import annotations

from typing import Literal

# --- Order ---
ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED"
ORDER_CREATED = "ORDER_CREATED"

# --- Automation ---
AUTOMATION_SUCCEEDED = "AUTOMATION_SUCCEEDED"
AUTOMATION_FAILED = "AUTOMATION_FAILED"
AUTOMATION_BLOCKED = "AUTOMATION_BLOCKED"

# --- Sale documents ---
SALE_DOCUMENT_CREATED = "SALE_DOCUMENT_CREATED"
SALE_DOCUMENT_NUMBER_ASSIGNED = "SALE_DOCUMENT_NUMBER_ASSIGNED"
SALE_DOCUMENT_CORRECTION_CREATED = "SALE_DOCUMENT_CORRECTION_CREATED"
SALE_DOCUMENT_FAILED = "SALE_DOCUMENT_FAILED"

# --- Warehouse documents (non-WMS writers only) ---
WAREHOUSE_DOCUMENT_CREATED = "WAREHOUSE_DOCUMENT_CREATED"
WAREHOUSE_DOCUMENT_NUMBER_ASSIGNED = "WAREHOUSE_DOCUMENT_NUMBER_ASSIGNED"
WAREHOUSE_DOCUMENT_FAILED = "WAREHOUSE_DOCUMENT_FAILED"

# --- Custom fields (Phase 2) ---
ORDER_CUSTOM_FIELD_CHANGED = "ORDER_CUSTOM_FIELD_CHANGED"
ORDER_CUSTOM_FIELD_FILE_ATTACHED = "ORDER_CUSTOM_FIELD_FILE_ATTACHED"
ORDER_CUSTOM_FIELD_FILE_REMOVED = "ORDER_CUSTOM_FIELD_FILE_REMOVED"

# --- Payments / methods (Phase 2) ---
ORDER_PAYMENT_REGISTERED = "ORDER_PAYMENT_REGISTERED"
ORDER_PAYMENT_STATUS_CHANGED = "ORDER_PAYMENT_STATUS_CHANGED"
ORDER_PAYMENT_METHOD_CHANGED = "ORDER_PAYMENT_METHOD_CHANGED"
ORDER_SHIPPING_METHOD_CHANGED = "ORDER_SHIPPING_METHOD_CHANGED"
# ORDER_REFUND_RECORDED — skipped (no non-WMS order-linked refund writer)

# --- Import (Phase 2) ---
ORDER_IMPORTED = "ORDER_IMPORTED"

# --- Manual OMS mutations (addresses / notes / lines) ---
ORDER_SHIPPING_ADDRESS_CHANGED = "ORDER_SHIPPING_ADDRESS_CHANGED"
ORDER_BILLING_ADDRESS_CHANGED = "ORDER_BILLING_ADDRESS_CHANGED"
ORDER_CUSTOMER_DATA_CHANGED = "ORDER_CUSTOMER_DATA_CHANGED"
ORDER_NOTE_ADDED = "ORDER_NOTE_ADDED"
ORDER_NOTE_UPDATED = "ORDER_NOTE_UPDATED"
ORDER_NOTE_DELETED = "ORDER_NOTE_DELETED"
ORDER_ITEM_ADDED = "ORDER_ITEM_ADDED"
ORDER_ITEM_REMOVED = "ORDER_ITEM_REMOVED"  # OMS narrative; WMS may also project same code via wms-evt
ORDER_ITEM_QUANTITY_CHANGED = "ORDER_ITEM_QUANTITY_CHANGED"
ORDER_ITEM_PRICE_CHANGED = "ORDER_ITEM_PRICE_CHANGED"
ORDER_ITEM_DISCOUNT_CHANGED = "ORDER_ITEM_DISCOUNT_CHANGED"
ORDER_ITEM_VAT_CHANGED = "ORDER_ITEM_VAT_CHANGED"
ORDER_PRIORITY_CHANGED = "ORDER_PRIORITY_CHANGED"
ORDER_DOCUMENT_SERIES_CHANGED = "ORDER_DOCUMENT_SERIES_CHANGED"
ORDER_WAREHOUSE_CHANGED = "ORDER_WAREHOUSE_CHANGED"
ORDER_BUNDLE_ADDED = "ORDER_BUNDLE_ADDED"

# --- Shipping / tracking / doc integration — reserved; emit only with real pipeline ---
# ORDER_SHIPMENT_CREATED / ORDER_WAYBILL_ASSIGNED / ORDER_TRACKING_STATUS_CHANGED /
# ORDER_SHIPMENT_FAILED / SALE_DOCUMENT_SENT_TO_INTEGRATION / SALE_DOCUMENT_EXPORT_FAILED
# — skipped in Phase 2 (WMS packing / stub fiscal only)

ActorKind = Literal["USER", "SYSTEM", "AUTOMATION", "INTEGRATION"]

ORDER_EVENT_CATEGORY: dict[str, str] = {
    ORDER_STATUS_CHANGED: "order",
    ORDER_CREATED: "order",
    AUTOMATION_SUCCEEDED: "automation",
    AUTOMATION_FAILED: "automation",
    AUTOMATION_BLOCKED: "automation",
    SALE_DOCUMENT_CREATED: "documents",
    SALE_DOCUMENT_NUMBER_ASSIGNED: "documents",
    SALE_DOCUMENT_CORRECTION_CREATED: "documents",
    SALE_DOCUMENT_FAILED: "documents",
    WAREHOUSE_DOCUMENT_CREATED: "documents",
    WAREHOUSE_DOCUMENT_NUMBER_ASSIGNED: "documents",
    WAREHOUSE_DOCUMENT_FAILED: "documents",
    ORDER_CUSTOM_FIELD_CHANGED: "order",
    ORDER_CUSTOM_FIELD_FILE_ATTACHED: "order",
    ORDER_CUSTOM_FIELD_FILE_REMOVED: "order",
    ORDER_PAYMENT_REGISTERED: "payments",
    ORDER_PAYMENT_STATUS_CHANGED: "payments",
    ORDER_PAYMENT_METHOD_CHANGED: "order",
    ORDER_SHIPPING_METHOD_CHANGED: "order",
    ORDER_IMPORTED: "order",
    ORDER_SHIPPING_ADDRESS_CHANGED: "order",
    ORDER_BILLING_ADDRESS_CHANGED: "order",
    ORDER_CUSTOMER_DATA_CHANGED: "order",
    ORDER_NOTE_ADDED: "order",
    ORDER_NOTE_UPDATED: "order",
    ORDER_NOTE_DELETED: "order",
    ORDER_ITEM_ADDED: "order",
    ORDER_ITEM_REMOVED: "order",
    ORDER_ITEM_QUANTITY_CHANGED: "order",
    ORDER_ITEM_PRICE_CHANGED: "order",
    ORDER_ITEM_DISCOUNT_CHANGED: "order",
    ORDER_ITEM_VAT_CHANGED: "order",
    ORDER_PRIORITY_CHANGED: "order",
    ORDER_DOCUMENT_SERIES_CHANGED: "order",
    ORDER_WAREHOUSE_CHANGED: "order",
    ORDER_BUNDLE_ADDED: "order",
}

ORDER_EVENT_TITLES_PL: dict[str, str] = {
    ORDER_STATUS_CHANGED: "Zmiana statusu",
    ORDER_CREATED: "Utworzenie zamówienia",
    AUTOMATION_SUCCEEDED: "Automatyzacja",
    AUTOMATION_FAILED: "Automatyzacja",
    AUTOMATION_BLOCKED: "Automatyzacja",
    SALE_DOCUMENT_CREATED: "Dokument sprzedaży",
    SALE_DOCUMENT_NUMBER_ASSIGNED: "Numer dokumentu",
    SALE_DOCUMENT_CORRECTION_CREATED: "Korekta dokumentu",
    SALE_DOCUMENT_FAILED: "Dokument sprzedaży",
    WAREHOUSE_DOCUMENT_CREATED: "Dokument magazynowy",
    WAREHOUSE_DOCUMENT_NUMBER_ASSIGNED: "Numer dokumentu magazynowego",
    WAREHOUSE_DOCUMENT_FAILED: "Dokument magazynowy",
    ORDER_CUSTOM_FIELD_CHANGED: "Pole dodatkowe",
    ORDER_CUSTOM_FIELD_FILE_ATTACHED: "Plik pola dodatkowego",
    ORDER_CUSTOM_FIELD_FILE_REMOVED: "Plik pola dodatkowego",
    ORDER_PAYMENT_REGISTERED: "Płatność",
    ORDER_PAYMENT_STATUS_CHANGED: "Status płatności",
    ORDER_PAYMENT_METHOD_CHANGED: "Metoda płatności",
    ORDER_SHIPPING_METHOD_CHANGED: "Metoda dostawy",
    ORDER_IMPORTED: "Import zamówienia",
    ORDER_SHIPPING_ADDRESS_CHANGED: "Adres dostawy",
    ORDER_BILLING_ADDRESS_CHANGED: "Adres faktury",
    ORDER_CUSTOMER_DATA_CHANGED: "Klient",
    ORDER_NOTE_ADDED: "Notatka",
    ORDER_NOTE_UPDATED: "Notatka",
    ORDER_NOTE_DELETED: "Notatka",
    ORDER_ITEM_ADDED: "Pozycja zamówienia",
    ORDER_ITEM_REMOVED: "Pozycja zamówienia",
    ORDER_ITEM_QUANTITY_CHANGED: "Pozycja zamówienia",
    ORDER_ITEM_PRICE_CHANGED: "Pozycja zamówienia",
    ORDER_ITEM_DISCOUNT_CHANGED: "Pozycja zamówienia",
    ORDER_ITEM_VAT_CHANGED: "Pozycja zamówienia",
    ORDER_PRIORITY_CHANGED: "Priorytet",
    ORDER_DOCUMENT_SERIES_CHANGED: "Seria dokumentu",
    ORDER_WAREHOUSE_CHANGED: "Magazyn",
    ORDER_BUNDLE_ADDED: "Zestaw",
}

ORDER_EVENT_CODES: frozenset[str] = frozenset(ORDER_EVENT_CATEGORY.keys())
