"""Canonical Order › Logi event codes (Activity Log SSOT).

Domain tables remain detail SSOT; these codes are order-facing timeline summaries only.
"""

from __future__ import annotations

from typing import Literal

# --- Order ---
ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED"

# --- Automation ---
AUTOMATION_SUCCEEDED = "AUTOMATION_SUCCEEDED"
AUTOMATION_FAILED = "AUTOMATION_FAILED"
AUTOMATION_BLOCKED = "AUTOMATION_BLOCKED"

# --- Sale documents ---
SALE_DOCUMENT_CREATED = "SALE_DOCUMENT_CREATED"
SALE_DOCUMENT_NUMBER_ASSIGNED = "SALE_DOCUMENT_NUMBER_ASSIGNED"
SALE_DOCUMENT_CORRECTION_CREATED = "SALE_DOCUMENT_CORRECTION_CREATED"
SALE_DOCUMENT_FAILED = "SALE_DOCUMENT_FAILED"

# --- Warehouse documents (non-WMS writers only) ---
WAREHOUSE_DOCUMENT_CREATED = "WAREHOUSE_DOCUMENT_CREATED"
WAREHOUSE_DOCUMENT_NUMBER_ASSIGNED = "WAREHOUSE_DOCUMENT_NUMBER_ASSIGNED"
WAREHOUSE_DOCUMENT_FAILED = "WAREHOUSE_DOCUMENT_FAILED"

# --- Custom fields (Phase 2) ---
ORDER_CUSTOM_FIELD_CHANGED = "ORDER_CUSTOM_FIELD_CHANGED"
ORDER_CUSTOM_FIELD_FILE_ATTACHED = "ORDER_CUSTOM_FIELD_FILE_ATTACHED"
ORDER_CUSTOM_FIELD_FILE_REMOVED = "ORDER_CUSTOM_FIELD_FILE_REMOVED"

# --- Payments / methods (Phase 2) ---
ORDER_PAYMENT_REGISTERED = "ORDER_PAYMENT_REGISTERED"
ORDER_PAYMENT_STATUS_CHANGED = "ORDER_PAYMENT_STATUS_CHANGED"
ORDER_PAYMENT_METHOD_CHANGED = "ORDER_PAYMENT_METHOD_CHANGED"
ORDER_SHIPPING_METHOD_CHANGED = "ORDER_SHIPPING_METHOD_CHANGED"
# ORDER_REFUND_RECORDED — skipped (no non-WMS order-linked refund writer)

# --- Import (Phase 2) ---
ORDER_IMPORTED = "ORDER_IMPORTED"

# --- Shipping / tracking / doc integration — reserved; emit only with real pipeline ---
# ORDER_SHIPMENT_CREATED / ORDER_WAYBILL_ASSIGNED / ORDER_TRACKING_STATUS_CHANGED /
# ORDER_SHIPMENT_FAILED / SALE_DOCUMENT_SENT_TO_INTEGRATION / SALE_DOCUMENT_EXPORT_FAILED
# — skipped in Phase 2 (WMS packing / stub fiscal only)

ActorKind = Literal["USER", "SYSTEM", "AUTOMATION", "INTEGRATION"]

ORDER_EVENT_CATEGORY: dict[str, str] = {
    ORDER_STATUS_CHANGED: "order",
    AUTOMATION_SUCCEEDED: "automation",
    AUTOMATION_FAILED: "automation",
    AUTOMATION_BLOCKED: "automation",
    SALE_DOCUMENT_CREATED: "documents",
    SALE_DOCUMENT_NUMBER_ASSIGNED: "documents",
    SALE_DOCUMENT_CORRECTION_CREATED: "documents",
    SALE_DOCUMENT_FAILED: "documents",
    WAREHOUSE_DOCUMENT_CREATED: "documents",
    WAREHOUSE_DOCUMENT_NUMBER_ASSIGNED: "documents",
    WAREHOUSE_DOCUMENT_FAILED: "documents",
    ORDER_CUSTOM_FIELD_CHANGED: "order",
    ORDER_CUSTOM_FIELD_FILE_ATTACHED: "order",
    ORDER_CUSTOM_FIELD_FILE_REMOVED: "order",
    ORDER_PAYMENT_REGISTERED: "payments",
    ORDER_PAYMENT_STATUS_CHANGED: "payments",
    ORDER_PAYMENT_METHOD_CHANGED: "order",
    ORDER_SHIPPING_METHOD_CHANGED: "order",
    ORDER_IMPORTED: "order",
}

ORDER_EVENT_TITLES_PL: dict[str, str] = {
    ORDER_STATUS_CHANGED: "Zmiana statusu",
    AUTOMATION_SUCCEEDED: "Automatyzacja",
    AUTOMATION_FAILED: "Automatyzacja",
    AUTOMATION_BLOCKED: "Automatyzacja",
    SALE_DOCUMENT_CREATED: "Dokument sprzedaży",
    SALE_DOCUMENT_NUMBER_ASSIGNED: "Numer dokumentu",
    SALE_DOCUMENT_CORRECTION_CREATED: "Korekta dokumentu",
    SALE_DOCUMENT_FAILED: "Dokument sprzedaży",
    WAREHOUSE_DOCUMENT_CREATED: "Dokument magazynowy",
    WAREHOUSE_DOCUMENT_NUMBER_ASSIGNED: "Numer dokumentu magazynowego",
    WAREHOUSE_DOCUMENT_FAILED: "Dokument magazynowy",
    ORDER_CUSTOM_FIELD_CHANGED: "Pole dodatkowe",
    ORDER_CUSTOM_FIELD_FILE_ATTACHED: "Plik pola dodatkowego",
    ORDER_CUSTOM_FIELD_FILE_REMOVED: "Plik pola dodatkowego",
    ORDER_PAYMENT_REGISTERED: "Płatność",
    ORDER_PAYMENT_STATUS_CHANGED: "Status płatności",
    ORDER_PAYMENT_METHOD_CHANGED: "Metoda płatności",
    ORDER_SHIPPING_METHOD_CHANGED: "Metoda dostawy",
    ORDER_IMPORTED: "Import zamówienia",
}

ORDER_EVENT_CODES: frozenset[str] = frozenset(ORDER_EVENT_CATEGORY.keys())
