"""Printing MVP — shared status and type constants."""

from __future__ import annotations

PRINTER_TYPE_A4 = "a4"
PRINTER_TYPE_LABEL = "label"
PRINTER_TYPE_RECEIPT = "receipt"
PRINTER_TYPE_OTHER = "other"

PRINTER_TYPES = (
    PRINTER_TYPE_A4,
    PRINTER_TYPE_LABEL,
    PRINTER_TYPE_RECEIPT,
    PRINTER_TYPE_OTHER,
)

JOB_STATUS_PENDING = "pending"
JOB_STATUS_PROCESSING = "processing"
JOB_STATUS_PRINTED = "printed"
JOB_STATUS_FAILED = "failed"
JOB_STATUS_CANCELLED = "cancelled"

PRINT_JOB_STATUSES = (
    JOB_STATUS_PENDING,
    JOB_STATUS_PROCESSING,
    JOB_STATUS_PRINTED,
    JOB_STATUS_FAILED,
    JOB_STATUS_CANCELLED,
)

JOB_TYPE_PDF = "pdf"
JOB_TYPE_LABEL = "label"
JOB_TYPE_RAW_ZPL = "raw_zpl"
JOB_TYPE_RECEIPT = "receipt"
JOB_TYPE_TEST_PAGE = "test_page"

JOB_TYPES = (
    JOB_TYPE_PDF,
    JOB_TYPE_LABEL,
    JOB_TYPE_RAW_ZPL,
    JOB_TYPE_RECEIPT,
    JOB_TYPE_TEST_PAGE,
)

SOURCE_MODULE_DOCUMENTS = "documents"
SOURCE_MODULE_WAREHOUSE = "warehouse"
SOURCE_MODULE_LABELS = "labels"
SOURCE_MODULE_ORDERS = "orders"
SOURCE_MODULE_PRODUCTION = "production"
SOURCE_MODULE_SETTINGS = "settings"
SOURCE_MODULE_SYSTEM = "system"

SOURCE_MODULES = (
    SOURCE_MODULE_DOCUMENTS,
    SOURCE_MODULE_WAREHOUSE,
    SOURCE_MODULE_LABELS,
    SOURCE_MODULE_ORDERS,
    SOURCE_MODULE_PRODUCTION,
    SOURCE_MODULE_SETTINGS,
    SOURCE_MODULE_SYSTEM,
)

OFFLINE_THRESHOLD_MINUTES = 2
STALE_HEARTBEAT_SECONDS = 60

RETRYABLE_JOB_STATUSES = frozenset({JOB_STATUS_FAILED, JOB_STATUS_PRINTED, JOB_STATUS_CANCELLED})
CANCELLABLE_JOB_STATUSES = frozenset({JOB_STATUS_PENDING, JOB_STATUS_PROCESSING})
