import type { WmsSettingsSearchEntry } from "./types";

const T = {
  general: "Ogólne",
  packing: "Pakowanie",
  picking: "Zbieranie",
  direct_sales: "Sprzedaż bezpośrednia",
  returns: "Zwroty",
  receiving: "Przyjęcia",
  production: "Produkcja",
  smart_matching: "Smart Matching",
  three_d_matching: "Dopasowanie przestrzenne",
} as const;

function e(
  partial: Omit<WmsSettingsSearchEntry, "tabLabel"> & { tabId: keyof typeof T },
): WmsSettingsSearchEntry {
  return { ...partial, tabLabel: T[partial.tabId] };
}

/**
 * Global searchable registry for Ustawienia WMS.
 * Keep `id` in sync with `data-wms-setting-id` on fields ({@link WmsSettingField}).
 */
export const WMS_SETTINGS_SEARCH_CATALOG: WmsSettingsSearchEntry[] = [
  e({
    id: "general.font_size_base",
    label: "Wielkość czcionki w nowych widokach trybów (ustawienie ogólne)",
    tabId: "general",
    sectionId: "wms-general-typography",
    sectionLabel: "Wielkość czcionki",
    keywords: ["czcionka", "font", "typografia", "ogólne"],
  }),
  e({
    id: "general.font_size_location",
    label: "Wielkość czcionki dla elementu wskazującego lokalizację",
    tabId: "general",
    sectionId: "wms-general-typography",
    sectionLabel: "Wielkość czcionki",
    keywords: ["lokalizacja", "czcionka", "font"],
  }),
  e({
    id: "general.font_size_quantity",
    label: "Wielkość czcionki dla elementu wskazującego ilości",
    tabId: "general",
    sectionId: "wms-general-typography",
    sectionLabel: "Wielkość czcionki",
    keywords: ["ilość", "czcionka", "font", "szt"],
  }),
  // Packing — Sellasist canonical labels
  e({
    id: "packing.layout_mode",
    label: "Wybierz układ",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
    keywords: ["układ", "layout"],
  }),
  e({
    id: "packing.customer_comment_style",
    label: "Wygląd komentarzy klienta",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.sales_document_preview",
    label: "Widok dokumentu sprzedaży",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.packed_products_extra_list",
    label: "Dodatkowa lista produktów spakowanych",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.product_display_mode",
    label: "Wygląd produktów na liście do spakowania",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.show_product_image",
    label: "Zdjęcie produktu na liście do spakowania",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.show_product_location",
    label: "Wyświetlaj lokalizację produktów",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.location_badge_position",
    label: "Umiejscowienie informacji o lokalizacji na produkcie",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.automation_buttons_position",
    label: "Położenie przycisków aktywatorów automatyzacji",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.move_packed_to_bottom",
    label: "Przesuwaj spakowane produkty na koniec listy",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.show_order_phone",
    label: "Wyświetlaj numer telefonu",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
    keywords: ["telefon", "phone"],
  }),
  e({
    id: "packing.show_order_value",
    label: "Wyświetlaj wartość zamówienia",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
    keywords: ["wartość", "kwota"],
  }),
  e({
    id: "packing.show_shipping_address",
    label: "Wyświetlaj adres dostawy",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
    keywords: ["adres", "dostawa"],
  }),
  e({
    id: "packing.show_stock",
    label: "Wyświetlaj stan magazynowy w produktach",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.show_ean",
    label: "Wyświetlaj EAN w produktach",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.show_symbol",
    label: "Wyświetlaj symbol w produkcie",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.show_catalog_number",
    label: "Wyświetlaj numer katalogowy w produktach",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.orders_list_layout",
    label: "Wybierz układ listy zamówień w trybie pakowania",
    tabId: "packing",
    sectionId: "wms-pack-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "packing.start_status_id",
    label: "Status zamówienia do rozpoczęcia pakowania",
    tabId: "packing",
    sectionId: "wms-pack-process",
    sectionLabel: "Proces pakowania",
  }),
  e({
    id: "packing.allowed_start_status_ids",
    label: "Statusy zamówienia do rozpoczęcia pakowania (wiele)",
    tabId: "packing",
    sectionId: "wms-pack-process",
    sectionLabel: "Proces pakowania",
  }),
  e({
    id: "packing.packed_status_id",
    label: "Status dla spakowanego zamówienia",
    tabId: "packing",
    sectionId: "wms-pack-process",
    sectionLabel: "Proces pakowania",
  }),
  e({
    id: "packing.missing_status_id",
    label: "Status dla braków w zamówieniu",
    tabId: "packing",
    sectionId: "wms-pack-process",
    sectionLabel: "Proces pakowania",
  }),
  e({
    id: "packing.auto_create_document",
    label: "Wystaw dokument sprzedaży",
    tabId: "packing",
    sectionId: "wms-pack-automation",
    sectionLabel: "Automatyzacja",
  }),
  e({
    id: "packing.auto_generate_shipment",
    label: "Wygeneruj list przewozowy",
    tabId: "packing",
    sectionId: "wms-pack-automation",
    sectionLabel: "Automatyzacja",
  }),
  e({
    id: "packing.auto_print_document",
    label: "Wydrukuj / pobierz dokument sprzedaży",
    tabId: "packing",
    sectionId: "wms-pack-automation",
    sectionLabel: "Automatyzacja",
  }),
  e({
    id: "packing.auto_print_label",
    label: "Wydrukuj / pobierz list przewozowy",
    tabId: "packing",
    sectionId: "wms-pack-automation",
    sectionLabel: "Automatyzacja",
  }),
  e({
    id: "packing.auto_change_order_status",
    label: "Zmień status zamówienia",
    tabId: "packing",
    sectionId: "wms-pack-automation",
    sectionLabel: "Automatyzacja",
  }),
  e({
    id: "packing.packer_is_not_picker",
    label: "Osoba pakująca nie jest zbieraczem",
    tabId: "packing",
    sectionId: "wms-pack-general",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "packing.require_notes_popup",
    label: "Otwieraj notatki w wyskakującym oknie",
    tabId: "packing",
    sectionId: "wms-pack-general",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "packing.show_all_notes",
    label: "Pokazuj wszystkie notatki",
    tabId: "packing",
    sectionId: "wms-pack-general",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "packing.sales_document_type",
    label: "Dokument sprzedaży",
    tabId: "packing",
    sectionId: "wms-pack-shipments-docs",
    sectionLabel: "Przesyłki i dokumenty",
  }),
  e({
    id: "packing.enable_multi_parcel",
    label: "Włącz wielopaczkowość",
    tabId: "packing",
    sectionId: "wms-pack-shipments-docs",
    sectionLabel: "Przesyłki i dokumenty",
  }),
  e({
    id: "packing.main_packing_warehouse",
    label: "Główny magazyn do pakowania",
    tabId: "packing",
    sectionId: "wms-pack-general",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "packing.show_automation_buttons",
    label: "Wyświetlaj Aktywatory Automatyzacji podczas pakowania zamówienia",
    tabId: "packing",
    sectionId: "wms-pack-automation",
    sectionLabel: "Automatyzacja",
  }),
  e({
    id: "packing.effect_after_auto_actions",
    label: "Efekt po wykonaniu akcji automatycznych",
    tabId: "packing",
    sectionId: "wms-pack-process",
    sectionLabel: "Proces pakowania",
    keywords: ["następne", "lista", "zostań"],
  }),

  // Picking
  e({
    id: "picking.after_batch_complete_action",
    label: "Akcja po zebraniu zbioru zamówień",
    description: "Co zrobić po prawidłowym zakończeniu zbioru",
    tabId: "picking",
    sectionId: "wms-pick-queue",
    sectionLabel: "Lista zleceń",
    groupLabel: "Akcja po zebraniu zbioru zamówień",
    keywords: ["zbiór", "przydziel", "wybór typu", "zostań"],
  }),
  e({
    id: "picking.require_product_scan",
    label: "Wymagane skanowanie produktu przynajmniej jeden raz",
    tabId: "picking",
    sectionId: "wms-pick-scan",
    sectionLabel: "Walidacja zbierania",
  }),
  e({
    id: "picking.require_location_scan",
    label: "Wymagane skanowanie lokalizacji",
    tabId: "picking",
    sectionId: "wms-pick-scan",
    sectionLabel: "Walidacja zbierania",
  }),
  e({
    id: "picking.allow_products_without_ean",
    label: "Produkty bez kodu EAN",
    tabId: "picking",
    sectionId: "wms-pick-scan",
    sectionLabel: "Walidacja zbierania",
  }),
  e({
    id: "picking.pre_assign_validation_status",
    label: "Status po błędzie walidacji",
    tabId: "picking",
    sectionId: "wms-pick-scan",
    sectionLabel: "Walidacja zbierania",
  }),
  e({
    id: "picking.shortage_reported_status",
    label: "Status po zakończeniu zbierania z brakiem",
    tabId: "picking",
    sectionId: "wms-pick-shortage",
    sectionLabel: "Braki",
  }),
  e({
    id: "picking.recovery_completed_status",
    label: "Status po rozwiązaniu wszystkich braków",
    tabId: "picking",
    sectionId: "wms-pick-shortage",
    sectionLabel: "Braki",
  }),

  // Direct sales
  e({
    id: "direct_sales.enabled",
    label: "Włącz sprzedaż bezpośrednią",
    tabId: "direct_sales",
    sectionId: "ds-general",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "direct_sales.default_order_status_id",
    label: "Status zamówienia sprzedaży",
    tabId: "direct_sales",
    sectionId: "ds-general",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "direct_sales.default_document_type",
    label: "Typ dokumentu domyślny",
    tabId: "direct_sales",
    sectionId: "ds-general",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "direct_sales.auto_start_new_session",
    label: "Automatycznie rozpocznij nową sesję po zamknięciu potwierdzenia sprzedaży",
    tabId: "direct_sales",
    sectionId: "ds-general",
    sectionLabel: "Ogólne",
    keywords: ["sesja", "potwierdzenie"],
  }),
  e({
    id: "direct_sales.allow_oversell",
    label: "Pozwalaj sprzedawać ponad stan magazynowy",
    tabId: "direct_sales",
    sectionId: "ds-stock",
    sectionLabel: "Stany magazynowe",
  }),
  e({
    id: "direct_sales.scanner_mode",
    label: "Włącz tryb skanera",
    tabId: "direct_sales",
    sectionId: "ds-terminal",
    sectionLabel: "Zaawansowane",
    keywords: ["tryb", "skaner"],
  }),

  // Returns / receiving / production
  e({
    id: "returns.mode",
    label: "Tryb obsługi zwrotów",
    tabId: "returns",
    sectionId: "wms-returns-workflow-mode",
    sectionLabel: "Ogólne",
    keywords: ["tryb"],
  }),
  e({
    id: "returns.z_pz_print_label",
    label: "Drukuj etykietę po zamknięciu Z-PZ",
    tabId: "returns",
    sectionId: "wms-returns-z-pz-label",
    sectionLabel: "Przyjęcie",
  }),
  e({
    id: "receiving.require_dimensions",
    label: "Wymagaj wymiarów produktu",
    tabId: "receiving",
    sectionId: "wms-receiving-product-validation",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "receiving.require_weight",
    label: "Wymagaj wagi produktu",
    tabId: "receiving",
    sectionId: "wms-receiving-product-validation",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "production.forecast_strategy",
    label: "Strategia prognozy",
    tabId: "production",
    sectionId: "wms-production-forecast",
    sectionLabel: "Prognozowanie i zapas",
  }),

  // Smart / 3D
  e({
    id: "smart.packaging_suggestions_enabled",
    label: "Włącz propozycje opakowań do zamówień",
    tabId: "smart_matching",
    sectionId: "wms-smart-config",
    sectionLabel: "Ogólne",
    keywords: ["smart", "matching", "propozycje"],
  }),
  e({
    id: "smart.identical_orders_threshold",
    label: "Tryb Smart Matching",
    tabId: "smart_matching",
    sectionId: "wms-smart-config",
    sectionLabel: "Ogólne",
    groupLabel: "Tryb Smart Matching",
    keywords: ["tryb", "smart", "próg", "uczenie"],
  }),
  e({
    id: "smart.proposal_init_status",
    label: "Status inicjujący propozycję opakowania",
    tabId: "smart_matching",
    sectionId: "wms-smart-config",
    sectionLabel: "Ogólne",
    keywords: ["status", "smart"],
  }),
  e({
    id: "smart.auto_label_enabled",
    label: "Automatyczne generowanie etykiet",
    tabId: "smart_matching",
    sectionId: "wms-smart-config",
    sectionLabel: "Ogólne",
    keywords: ["etykiety", "list", "smart"],
  }),
  e({
    id: "three_d.matching_strategy",
    label: "Strategia dopasowania",
    tabId: "three_d_matching",
    sectionId: "wms-3d-engine",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "three_d.dimension_tolerance_mm",
    label: "Tolerancja wymiarów (mm)",
    tabId: "three_d_matching",
    sectionId: "wms-3d-engine",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "three_d.allow_product_rotation",
    label: "Obracanie produktów w symulacji",
    tabId: "three_d_matching",
    sectionId: "wms-3d-engine",
    sectionLabel: "Ogólne",
  }),
];
