import type { WmsSettingsSearchEntry } from "./types";

const T = {
  packing: "Pakowanie",
  picking: "Zbieranie",
  direct_sales: "Sprzedaż bezpośrednia",
  returns: "Zwroty",
  receiving: "Przyjęcia",
  production: "Produkcja",
  smart_matching: "Smart Matching",
  three_d_matching: "Dopasowanie przestrzenne",
} as const;

function e(
  partial: Omit<WmsSettingsSearchEntry, "tabLabel"> & { tabId: keyof typeof T },
): WmsSettingsSearchEntry {
  return { ...partial, tabLabel: T[partial.tabId] };
}

/**
 * Global searchable registry for Ustawienia WMS.
 * Keep `id` in sync with `data-wms-setting-id` on fields ({@link WmsSettingField}).
 */
export const WMS_SETTINGS_SEARCH_CATALOG: WmsSettingsSearchEntry[] = [
  // Packing — groups (searchable)
  e({
    id: "packing.group.layout_general",
    label: "Ogólny układ",
    description: "Szerokość obszaru roboczego, lista produktów i pozycja przycisków automatyzacji.",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "A. Ogólny układ",
    keywords: ["układ", "layout"],
  }),
  e({
    id: "packing.group.customer_panel",
    label: "Panel klienta",
    description: "Komentarz klienta, podgląd dokumentu sprzedaży.",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "B. Panel klienta i dokumentów",
  }),
  e({
    id: "packing.group.products_view",
    label: "Produkty",
    description: "Widok produktów podczas pakowania.",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "C. Widok produktów podczas pakowania",
  }),

  // Packing — Widok fields
  e({
    id: "packing.layout_mode",
    label: "Tryb układu",
    description: "Szerokość obszaru roboczego",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "A. Ogólny układ",
    keywords: ["układ", "layout", "tryb"],
  }),
  e({
    id: "packing.automation_buttons_position",
    label: "Pozycja przycisków automatyzacji",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "A. Ogólny układ",
  }),
  e({
    id: "packing.product_display_mode",
    label: "Lista produktów (widok siatki / listy)",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "A. Ogólny układ",
  }),
  e({
    id: "packing.customer_comment_style",
    label: "Komentarz klienta",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "B. Panel klienta i dokumentów",
  }),
  e({
    id: "packing.sales_document_preview",
    label: "Podgląd dokumentu sprzedaży",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "B. Panel klienta i dokumentów",
  }),
  e({
    id: "packing.packed_products_extra_list",
    label: "Dodatkowa lista spakowanych produktów",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "B. Panel klienta i dokumentów",
  }),
  e({
    id: "packing.location_badge_position",
    label: "Pozycja plakietki lokalizacji",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "C. Widok produktów podczas pakowania",
  }),
  e({
    id: "packing.show_product_image",
    label: "Pokazuj zdjęcie produktu",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "C. Widok produktów podczas pakowania",
  }),
  e({
    id: "packing.show_product_location",
    label: "Pokazuj lokalizację produktu",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "C. Widok produktów podczas pakowania",
  }),
  e({
    id: "packing.move_packed_to_bottom",
    label: "Przenieś spakowane na dół listy",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "C. Widok produktów podczas pakowania",
  }),
  e({
    id: "packing.show_stock",
    label: "Stan magazynowy (API)",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "C. Widok produktów podczas pakowania",
  }),
  e({
    id: "packing.show_ean",
    label: "EAN (API)",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "C. Widok produktów podczas pakowania",
  }),
  e({
    id: "packing.show_symbol",
    label: "SKU / symbol (API)",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "C. Widok produktów podczas pakowania",
  }),
  e({
    id: "packing.show_catalog_number",
    label: "Numer katalogowy (API)",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "C. Widok produktów podczas pakowania",
  }),
  e({
    id: "packing.orders_list_layout",
    label: "Układ listy zamówień",
    tabId: "packing",
    sectionId: "wms-pack-appearance",
    sectionLabel: "Widok",
    groupLabel: "D. Widok listy zamówień",
    keywords: ["układ"],
  }),

  // Packing — Workflow / Automation / General
  e({
    id: "packing.start_status_id",
    label: "Status na początku pakowania",
    tabId: "packing",
    sectionId: "wms-pack-workflow",
    sectionLabel: "Workflow",
  }),
  e({
    id: "packing.packed_status_id",
    label: "Status po spakowaniu",
    tabId: "packing",
    sectionId: "wms-pack-workflow",
    sectionLabel: "Workflow",
  }),
  e({
    id: "packing.missing_status_id",
    label: "Status przy brakach",
    tabId: "packing",
    sectionId: "wms-pack-workflow",
    sectionLabel: "Workflow",
  }),
  e({
    id: "packing.auto_generate_shipment",
    label: "Generuj przesyłkę",
    tabId: "packing",
    sectionId: "wms-pack-automation",
    sectionLabel: "Automatyzacja",
    groupLabel: "Czynności po zakończeniu pakowania",
  }),
  e({
    id: "packing.auto_create_document",
    label: "Utwórz dokument sprzedaży",
    tabId: "packing",
    sectionId: "wms-pack-automation",
    sectionLabel: "Automatyzacja",
  }),
  e({
    id: "packing.auto_print_label",
    label: "Drukuj etykietę",
    tabId: "packing",
    sectionId: "wms-pack-automation",
    sectionLabel: "Automatyzacja",
  }),
  e({
    id: "packing.execution_mode",
    label: "Sposób wykonania",
    tabId: "packing",
    sectionId: "wms-pack-automation",
    sectionLabel: "Automatyzacja",
  }),
  e({
    id: "packing.packer_is_not_picker",
    label: "Pakujący ≠ kompletujący",
    tabId: "packing",
    sectionId: "wms-pack-permissions",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "packing.require_notes_popup",
    label: "Wymuś okno z notatkami",
    tabId: "packing",
    sectionId: "wms-pack-permissions",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "packing.sales_document_type",
    label: "Typ dokumentu (preferencja, lokalnie)",
    tabId: "packing",
    sectionId: "wms-pack-documents",
    sectionLabel: "Integracje",
  }),
  e({
    id: "packing.enable_multi_parcel",
    label: "Wiele paczek (multi-parcel)",
    tabId: "packing",
    sectionId: "wms-pack-labels",
    sectionLabel: "Drukowanie",
  }),
  e({
    id: "packing.main_packing_warehouse",
    label: "Główny magazyn pakowania",
    tabId: "packing",
    sectionId: "wms-pack-advanced",
    sectionLabel: "Zaawansowane",
  }),

  // Picking
  e({
    id: "picking.compact_mode",
    label: "Tryb kompaktowy",
    tabId: "picking",
    sectionId: "wms-pick-view",
    sectionLabel: "Widok",
    groupLabel: "Układ listy",
    keywords: ["tryb", "widok"],
  }),
  e({
    id: "picking.list_density",
    label: "Gęstość listy",
    tabId: "picking",
    sectionId: "wms-pick-view",
    sectionLabel: "Widok",
  }),
  e({
    id: "picking.batch_management_mode",
    label: "Zarządzanie zbiorami",
    description: "Tryb kompletacji / zbiorów",
    tabId: "picking",
    sectionId: "wms-pick-queue",
    sectionLabel: "Lista zleceń",
    groupLabel: "Zarządzanie zbiorami",
    keywords: ["tryb", "kompletacja", "zbiór"],
  }),
  e({
    id: "picking.require_product_scan",
    label: "Wymagane skanowanie produktu przynajmniej jeden raz",
    tabId: "picking",
    sectionId: "wms-pick-scan",
    sectionLabel: "Terminal",
  }),
  e({
    id: "picking.require_location_scan",
    label: "Wymagane skanowanie lokalizacji",
    tabId: "picking",
    sectionId: "wms-pick-scan",
    sectionLabel: "Terminal",
  }),
  e({
    id: "picking.default_container_type",
    label: "Domyślny typ kontenera",
    tabId: "picking",
    sectionId: "wms-pick-carts",
    sectionLabel: "Metody zbierania",
  }),
  e({
    id: "picking.show_in_braki_after_shortage",
    label: "Pokaż zamówienie w zakładce Braki po zgłoszeniu braku",
    tabId: "picking",
    sectionId: "wms-pick-shortage",
    sectionLabel: "Braki",
  }),
  e({
    id: "picking.split_work_between_warehouses",
    label: "Rozdziel pracę między magazynami",
    tabId: "picking",
    sectionId: "wms-pick-warehouses",
    sectionLabel: "Magazyny",
  }),
  e({
    id: "picking.auto_start_next_order",
    label: "Auto: następne zamówienie",
    tabId: "picking",
    sectionId: "wms-pick-automation",
    sectionLabel: "Automatyzacja",
  }),
  e({
    id: "picking.debug_mode",
    label: "Tryb debug",
    tabId: "picking",
    sectionId: "wms-pick-advanced",
    sectionLabel: "Zaawansowane",
    keywords: ["tryb"],
  }),

  // Direct sales
  e({
    id: "direct_sales.enabled",
    label: "Włącz sprzedaż bezpośrednią",
    tabId: "direct_sales",
    sectionId: "ds-general",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "direct_sales.default_document_type",
    label: "Typ dokumentu domyślny",
    tabId: "direct_sales",
    sectionId: "ds-general",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "direct_sales.allow_oversell",
    label: "Pozwalaj sprzedawać ponad stan magazynowy",
    tabId: "direct_sales",
    sectionId: "ds-stock",
    sectionLabel: "Stany magazynowe",
  }),
  e({
    id: "direct_sales.scanner_mode",
    label: "Włącz tryb skanera",
    tabId: "direct_sales",
    sectionId: "ds-terminal",
    sectionLabel: "Zaawansowane",
    keywords: ["tryb", "skaner"],
  }),

  // Returns / receiving / production
  e({
    id: "returns.mode",
    label: "Tryb obsługi zwrotów",
    tabId: "returns",
    sectionId: "wms-returns-workflow-mode",
    sectionLabel: "Ogólne",
    keywords: ["tryb"],
  }),
  e({
    id: "returns.z_pz_print_label",
    label: "Drukuj etykietę po zamknięciu Z-PZ",
    tabId: "returns",
    sectionId: "wms-returns-z-pz-label",
    sectionLabel: "Przyjęcie",
  }),
  e({
    id: "receiving.require_dimensions",
    label: "Wymagaj wymiarów produktu",
    tabId: "receiving",
    sectionId: "wms-receiving-product-validation",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "receiving.require_weight",
    label: "Wymagaj wagi produktu",
    tabId: "receiving",
    sectionId: "wms-receiving-product-validation",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "production.forecast_strategy",
    label: "Strategia prognozy",
    tabId: "production",
    sectionId: "wms-production-forecast",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "production.require_quality_control",
    label: "Kontrola jakości",
    tabId: "production",
    sectionId: "wms-production-terminal-required",
    sectionLabel: "Terminal",
  }),

  // Smart / 3D
  e({
    id: "smart.packaging_suggestions_enabled",
    label: "Włącz propozycje opakowań dla zamówień",
    description: "Tryb Smart Matching",
    tabId: "smart_matching",
    sectionId: "wms-smart-config",
    sectionLabel: "Ogólne",
    keywords: ["tryb", "smart", "matching"],
  }),
  e({
    id: "smart.identical_orders_threshold",
    label: "Wymagana liczba identycznych, spakowanych zamówień",
    tabId: "smart_matching",
    sectionId: "wms-smart-config",
    sectionLabel: "Ogólne",
    groupLabel: "Tryb Smart Matching — próg uczenia",
    keywords: ["tryb", "smart"],
  }),
  e({
    id: "three_d.matching_strategy",
    label: "Strategia dopasowania",
    tabId: "three_d_matching",
    sectionId: "wms-3d-engine",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "three_d.dimension_tolerance_mm",
    label: "Tolerancja wymiarów (mm)",
    tabId: "three_d_matching",
    sectionId: "wms-3d-engine",
    sectionLabel: "Ogólne",
  }),
  e({
    id: "three_d.allow_product_rotation",
    label: "Obracanie produktów w symulacji",
    tabId: "three_d_matching",
    sectionId: "wms-3d-engine",
    sectionLabel: "Ogólne",
  }),
];
