"""Production planning constants."""

from __future__ import annotations

TERMINAL_ORDER_STATUS = frozenset(
    {
        "SHIPPED",
        "COMPLETED",
        "CANCELLED",
        "CANCELLED_RETURN",
        "DELIVERED",
        "RETURNED",
        "ARCHIVED",
        "ZAKONCZONE",
        "ANULOWANE",
    }
)

TERMINAL_FULFILLMENT_STATE = frozenset(
    {
        "DELIVERED",
        "SHIPPED",
        "CANCELLED",
        "COMPLETED",
        "RETURNED",
        "ARCHIVED",
    }
)

PIPELINE_BATCH_MO_STATUSES = frozenset({"planned", "collecting", "in_progress", "putaway"})

DEFAULT_SALES_LOOKBACK_DAYS = 30
DEFAULT_COVERAGE_DAYS = 21
COVERAGE_DAY_PRESETS = (7, 14, 21, 30, 45, 60, 90)

MIN_COVERAGE_DAYS = 1
MAX_COVERAGE_DAYS = 365
MIN_SALES_LOOKBACK_DAYS = 7
MAX_SALES_LOOKBACK_DAYS = 365

FORECAST_STRATEGY_PERIOD_AVERAGE = "PERIOD_AVERAGE"
FORECAST_STRATEGY_WEIGHTED_AVERAGE = "WEIGHTED_AVERAGE"
FORECAST_STRATEGY_WEEKDAY_AVERAGE = "WEEKDAY_AVERAGE"
FORECAST_STRATEGY_MEDIAN = "MEDIAN"
FORECAST_STRATEGY_MAX_DAILY = "MAX_DAILY"
FORECAST_STRATEGY_AI_SMART = "AI_SMART"

FORECAST_STRATEGIES = (
    FORECAST_STRATEGY_PERIOD_AVERAGE,
    FORECAST_STRATEGY_WEIGHTED_AVERAGE,
    FORECAST_STRATEGY_WEEKDAY_AVERAGE,
    FORECAST_STRATEGY_MEDIAN,
    FORECAST_STRATEGY_MAX_DAILY,
    FORECAST_STRATEGY_AI_SMART,
)

DEFAULT_FORECAST_STRATEGY = FORECAST_STRATEGY_PERIOD_AVERAGE

PRIORITY_CRITICAL = "CRITICAL"
PRIORITY_HIGH = "HIGH"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_LOW = "LOW"

COVERAGE_COLOR_CRITICAL = "red"
COVERAGE_COLOR_WARNING = "orange"
COVERAGE_COLOR_OK = "green"
COVERAGE_COLOR_COMFORT = "blue"

HIGH_SALES_DAILY_THRESHOLD = 5.0
