"""Production planning constants."""

from __future__ import annotations

TERMINAL_ORDER_STATUS = frozenset(
    {
        "SHIPPED",
        "COMPLETED",
        "CANCELLED",
        "CANCELLED_RETURN",
        "DELIVERED",
        "RETURNED",
        "ARCHIVED",
        "ZAKONCZONE",
        "ANULOWANE",
    }
)

TERMINAL_FULFILLMENT_STATE = frozenset(
    {
        "DELIVERED",
        "SHIPPED",
        "CANCELLED",
        "COMPLETED",
        "RETURNED",
        "ARCHIVED",
    }
)

PIPELINE_BATCH_MO_STATUSES = frozenset({"planned", "collecting", "in_progress", "putaway"})

DEFAULT_SALES_LOOKBACK_DAYS = 30
DEFAULT_COVERAGE_DAYS = 21
COVERAGE_DAY_PRESETS = (7, 14, 21, 30, 45, 60, 90)

# Auto stock replenishment (nadprodukcja) — fixed coverage selector only
STOCK_REPLENISHMENT_COVERAGE_PRESETS = (1, 3, 7, 14)
DEFAULT_STOCK_REPLENISHMENT_COVERAGE_DAYS = 7

# Scheduler interval for automatic PLANNING replenishment (hours)
STOCK_REPLENISHMENT_INTERVAL_HOURLY = "hourly"
STOCK_REPLENISHMENT_INTERVAL_EVERY_3_HOURS = "every_3_hours"
STOCK_REPLENISHMENT_INTERVAL_EVERY_6_HOURS = "every_6_hours"
STOCK_REPLENISHMENT_INTERVAL_DAILY = "daily"
STOCK_REPLENISHMENT_INTERVAL_PRESETS = (
    STOCK_REPLENISHMENT_INTERVAL_HOURLY,
    STOCK_REPLENISHMENT_INTERVAL_EVERY_3_HOURS,
    STOCK_REPLENISHMENT_INTERVAL_EVERY_6_HOURS,
    STOCK_REPLENISHMENT_INTERVAL_DAILY,
)
DEFAULT_STOCK_REPLENISHMENT_INTERVAL = STOCK_REPLENISHMENT_INTERVAL_DAILY
STOCK_REPLENISHMENT_INTERVAL_HOURS = {
    STOCK_REPLENISHMENT_INTERVAL_HOURLY: 1,
    STOCK_REPLENISHMENT_INTERVAL_EVERY_3_HOURS: 3,
    STOCK_REPLENISHMENT_INTERVAL_EVERY_6_HOURS: 6,
    STOCK_REPLENISHMENT_INTERVAL_DAILY: 24,
}

MIN_COVERAGE_DAYS = 1
MAX_COVERAGE_DAYS = 365
MIN_SALES_LOOKBACK_DAYS = 7
MAX_SALES_LOOKBACK_DAYS = 365

FORECAST_STRATEGY_PERIOD_AVERAGE = "PERIOD_AVERAGE"
FORECAST_STRATEGY_WEIGHTED_AVERAGE = "WEIGHTED_AVERAGE"
FORECAST_STRATEGY_WEEKDAY_AVERAGE = "WEEKDAY_AVERAGE"

FORECAST_STRATEGIES = (
    FORECAST_STRATEGY_PERIOD_AVERAGE,
    FORECAST_STRATEGY_WEIGHTED_AVERAGE,
    FORECAST_STRATEGY_WEEKDAY_AVERAGE,
)

DEFAULT_FORECAST_STRATEGY = FORECAST_STRATEGY_PERIOD_AVERAGE

PRIORITY_CRITICAL = "CRITICAL"
PRIORITY_HIGH = "HIGH"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_LOW = "LOW"

COVERAGE_COLOR_CRITICAL = "red"
COVERAGE_COLOR_WARNING = "orange"
COVERAGE_COLOR_OK = "green"
COVERAGE_COLOR_COMFORT = "blue"

HIGH_SALES_DAILY_THRESHOLD = 5.0
