"""Task orchestration lifecycle constants."""

from ...models.wms_operational_task import (
    ORCH_ACTIVE,
    ORCH_ASSIGNED,
    ORCH_BLOCKED,
    ORCH_CANCELLED,
    ORCH_COMPLETED,
    ORCH_CREATED,
    ORCH_FAILED,
    ORCH_QUEUED,
    ORCH_WAITING,
    STATUS_CANCELLED,
    STATUS_DONE,
    STATUS_IN_PROGRESS,
    STATUS_OPEN,
)

VALID_TRANSITIONS: dict[str, set[str]] = {
    ORCH_CREATED: {ORCH_QUEUED, ORCH_CANCELLED},
    ORCH_QUEUED: {ORCH_ASSIGNED, ORCH_BLOCKED, ORCH_CANCELLED},
    ORCH_ASSIGNED: {ORCH_ACTIVE, ORCH_WAITING, ORCH_CANCELLED},
    ORCH_ACTIVE: {ORCH_COMPLETED, ORCH_FAILED, ORCH_BLOCKED, ORCH_WAITING},
    ORCH_BLOCKED: {ORCH_QUEUED, ORCH_WAITING, ORCH_CANCELLED},
    ORCH_WAITING: {ORCH_QUEUED, ORCH_ASSIGNED, ORCH_CANCELLED},
    ORCH_COMPLETED: set(),
    ORCH_FAILED: {ORCH_QUEUED},
    ORCH_CANCELLED: set(),
}

ORCH_TO_STATUS = {
    ORCH_CREATED: STATUS_OPEN,
    ORCH_QUEUED: STATUS_OPEN,
    ORCH_ASSIGNED: STATUS_IN_PROGRESS,
    ORCH_ACTIVE: STATUS_IN_PROGRESS,
    ORCH_BLOCKED: STATUS_OPEN,
    ORCH_WAITING: STATUS_OPEN,
    ORCH_COMPLETED: STATUS_DONE,
    ORCH_FAILED: STATUS_OPEN,
    ORCH_CANCELLED: STATUS_CANCELLED,
}
