import type { AssignedLocation } from "./warehouse";
import type { ProductDispositionStock } from "./productDispositionStock";

/** Normalized product row shared by list + edit page fetch (types only — safe for api/ imports). */
export type ProductListRow = {
  id: number;
  tenant_id?: number;
  name?: string;
  ean?: string;
  symbol?: string;
  length?: number;
  width?: number;
  height?: number;
  weight?: number;
  volume?: number;
  purchase_price?: number | null;
  extra_cost_packaging_net?: number | null;
  extra_cost_commission_percent?: number | null;
  extra_cost_other_net?: number | null;
  previous_purchase_price?: number | null;
  purchase_price_original?: number | null;
  purchase_currency?: string | null;
  last_purchase_date?: string | null;
  last_supplier_id?: number | null;
  last_supplier_brief?: { id: number; name: string } | null;
  last_purchase_currency?: string | null;
  sale_price?: number | null;
  manufacturer?: string | null;
  manufacturer_id?: number | null;
  manufacturer_brief?: { id: number; name: string; logo_url?: string | null } | null;
  default_supplier_id?: number | null;
  default_supplier_brief?: { id: number; name: string } | null;
  gpsr_responsible_name?: string | null;
  gpsr_responsible_email?: string | null;
  unit?: string | null;
  image_url?: string;
  assignedLocations?: AssignedLocation[];
  locations?: {
    id?: number;
    code?: string;
    name: string;
    quantity: number;
    warehouse_id?: number;
    storage_type?: string;
    location_uuid?: string | null;
  }[];
  inventory?: {
    location_id: number;
    location_code: string;
    location_type: string;
    quantity: number;
    batch?: string | null;
    expiry?: string | null;
    warehouse_id?: number;
    location_uuid?: string | null;
    stock_disposition?: string | null;
    disposition_badge?: string | null;
    warehouse_carrier_id?: number | null;
    carrier_code?: string | null;
    carrier_barcode?: string | null;
    carrier_is_mixed?: boolean;
  }[];
  label_template_id?: number | null;
  stock_quantity?: number;
  location_allocated_quantity?: number;
  unallocated_quantity?: number;
  reserved_quantity?: number;
  available_quantity?: number;
  disposition_stock?: ProductDispositionStock;
  commercially_sellable_qty?: number;
  sales_blocked_qty?: number;
  inventory_value?: number | null;
  average_purchase_price?: number | null;
  current_cost?: {
    purchase_net?: number | null;
    purchase_gross?: number | null;
    extra_cost_net?: number | null;
    landed_cost_net?: number | null;
    vat_percent?: number | null;
    sale_net?: number | null;
    sale_gross?: number | null;
    margin_value?: number | null;
    margin_percent?: number | null;
    updated_at?: string | null;
    source?: string | null;
  } | null;
  rotation_30d?: number;
  days_of_stock?: number | null;
  metadata_json?: Record<string, unknown> | null;
  min_pick_quantity?: number | null;
  max_pick_quantity?: number | null;
  min_reserve_quantity?: number | null;
  max_reserve_quantity?: number | null;
  enable_stock_alert?: boolean;
  min_total_stock?: number | null;
  bulk_ean?: string | null;
  units_per_carton?: number | null;
  carton_length_cm?: number | null;
  carton_width_cm?: number | null;
  carton_height_cm?: number | null;
  carton_weight_kg?: number | null;
  carton_volume_dm3?: number | null;
  product_orientation_type?: string | null;
  product_shape_type?: string | null;
  product_stack_compressible?: boolean | null;
  product_compressed_height_cm?: number | null;
  product_max_stack_weight?: number | null;
  product_stack_behavior?: string | null;
  orientation_type?: string | null;
  shape_type?: string | null;
  stack_compressible?: boolean | null;
  compressed_height_cm?: number | null;
  max_stack_weight?: number | null;
  stack_behavior?: string | null;
  carton_orientation_type?: string | null;
  carton_shape_type?: string | null;
  carton_stack_compressible?: boolean | null;
  carton_compressed_height_cm?: number | null;
  carton_max_stack_weight?: number | null;
  carton_stack_behavior?: string | null;
  track_batch?: boolean;
  track_expiry?: boolean;
  track_serial?: boolean;
  require_recv_height?: boolean;
  require_recv_width?: boolean;
  require_recv_length?: boolean;
  require_recv_weight?: boolean;
  require_recv_master_carton?: boolean;
  require_recv_master_carton_ean?: boolean;
  require_recv_master_carton_qty?: boolean;
  require_recv_master_carton_dims?: boolean;
  require_recv_master_carton_weight?: boolean;
  locations_load_incomplete?: boolean;
  detail_degraded?: boolean;
  detail_degraded_reason?: string | null;
};
