"""Printing module service-layer constants."""

from __future__ import annotations

from ...models.printing.constants import (
    JOB_STATUS_CANCELLED,
    JOB_STATUS_FAILED,
    JOB_STATUS_PENDING,
    JOB_STATUS_PRINTED,
    JOB_STATUS_PROCESSING,
    OFFLINE_THRESHOLD_MINUTES,
    PRINT_JOB_STATUSES,
    PRINTER_TYPE_A4,
    PRINTER_TYPE_LABEL,
    PRINTER_TYPE_OTHER,
    PRINTER_TYPE_RECEIPT,
    PRINTER_TYPES,
)

AGENT_TOKEN_PREFIX = "spt_"

ALLOWED_JOB_TRANSITIONS: dict[str, frozenset[str]] = {
    JOB_STATUS_PENDING: frozenset({JOB_STATUS_PROCESSING}),
    JOB_STATUS_PROCESSING: frozenset({JOB_STATUS_PRINTED, JOB_STATUS_FAILED}),
    JOB_STATUS_CANCELLED: frozenset({JOB_STATUS_PRINTED, JOB_STATUS_FAILED}),
}

DEFAULT_PRINTER_TYPE_FIELDS: dict[str, str] = {
    "a4_printer_id": PRINTER_TYPE_A4,
    "label_printer_id": PRINTER_TYPE_LABEL,
    "receipt_printer_id": PRINTER_TYPE_RECEIPT,
}

__all__ = [
    "AGENT_TOKEN_PREFIX",
    "ALLOWED_JOB_TRANSITIONS",
    "DEFAULT_PRINTER_TYPE_FIELDS",
    "JOB_STATUS_CANCELLED",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_PENDING",
    "JOB_STATUS_PRINTED",
    "JOB_STATUS_PROCESSING",
    "OFFLINE_THRESHOLD_MINUTES",
    "PRINT_JOB_STATUSES",
    "PRINTER_TYPE_A4",
    "PRINTER_TYPE_LABEL",
    "PRINTER_TYPE_OTHER",
    "PRINTER_TYPE_RECEIPT",
    "PRINTER_TYPES",
]
