"""Universal reservation kinds and allocation strategies."""

from __future__ import annotations

from typing import Literal

RESERVATION_KIND_SALES_ORDER = "SALES_ORDER"
RESERVATION_KIND_PRODUCTION_BATCH = "PRODUCTION_BATCH"
RESERVATION_KIND_PRODUCTION_ORDER = "PRODUCTION_ORDER"
RESERVATION_KIND_DIRECT_SALE = "DIRECT_SALE"
RESERVATION_KIND_TRANSFER = "TRANSFER"
RESERVATION_KIND_SOFT_HOLD = "SOFT_HOLD"

AllocationStrategy = Literal["FIFO", "FEFO", "LIFO"]
DEFAULT_ALLOCATION_STRATEGY: AllocationStrategy = "FEFO"

RESERVATION_STATUS_RESERVED = "reserved"
RESERVATION_STATUS_RELEASED = "released"
RESERVATION_STATUS_PICKED = "picked"
