/**
 * Centralized UI labels, table headers, and sidebar names.
 * Use for navigation, warehouse designer, label designer, and tables.
 */

export const UI_STRINGS = {
  app: {
    title: "WMS",
    titleSaaS: "WMS SaaS",
  },

  navigation: {
    dashboard: "Dashboard",
    products: "Produkty",
    inventory: "Stan magazynowy",
    orders: "Zamówienia",
    carts: "Wózki",
    import: "Import",
    fleetPlanner: "Planer floty",
    pickingWaves: "Fale kompletacji",
    warehouseDesigner: "Projektant Magazynu",
    barcodeManagement: "Etykiety / Kody kreskowe",
    labelSystem: "System Etykiet",
    setup: "Setup",
    analysis: "Analiza",
  },

  warehouse: {
    title: "Projektant Magazynu",
    tabs: {
      live: "Magazyn",
      edit: "Projektant",
    },
    /** Sub-tabs in Projektant Magazynu: only Magazyn and Layout (no Label Designer here). */
    designerSubTabs: {
      magazyn: "Magazyn",
      layoutDesigner: "Projektant Layoutu",
    },
    subTabs: {
      layout: "Layout Magazynu",
      labels: "Etykiety / Kody kreskowe",
    },
    columns: {
      name: "Nazwa",
      occupancy: "Zajętość (%)",
      occupancyDm3: "Zajętość (dm³)",
    },
    summary: {
      title: "PODSUMOWANIE PROJEKTU",
      totalCapacity: "Pojemność całkowita:",
      freeCapacity: "Wolna pojemność:",
      locationsBins: "Lokalizacje (biny):",
      reserveOverstock: "Rezerwa (overstock):",
      clickRackHint: "Kliknij regał, aby zobaczyć stan i zajętość.",
      totalRacks: "Regały:",
      totalBins: "Biny:",
      reserveCount: "w tym",
      reserveSuffix: "Rezerwa",
      dimensions: "Wymiary (W × D × H):",
      presetLabel: "Regał (preset)",
      rackCount: "Liczba regałów:",
      totalLocations: "Łącznie lokalizacji:",
      primaryLabel: "Podstawowe:",
      reserveLabel: "Rezerwa:",
    },
    selector: {
      selectWarehouse: "— wybierz magazyn —",
      newWarehouse: "+ Nowy magazyn",
      syncSaved: "Sync z DB",
      notSaved: "Nie zapisano",
      savedToDb: "Zapisano w DB",
      unsavedChanges: "Zmiany niezapisane",
    },
    modal: {
      newWarehouse: "Nowy magazyn",
      warehousePlaceholder: "np. Magazyn Główny",
      cancel: "Anuluj",
      create: "Utwórz",
    },
    rackSidebar: {
      catalog: "Layout i szablony",
      exportLocationsCsv: "Pobierz lokalizacje",
      rackSearchPlaceholder: "Szukaj regału...",
      currentRow: "Aktualny rząd",
      locationsPerLevelShort: "lok./poz.",
      visualElements: "Elementy wizualne",
      gapCm: "Odstęp (cm):",
      deleteTemplateConfirm: "Usunąć szablon z katalogu? Regały na planie pozostaną.",
      dm3: "dm³",
      newTemplate: "+ Nowy Szablon",
      rackList: "Lista regałów",
      noRacks: "Brak regałów",
      dragOntoPlan: "Przeciągnij na plan",
      noTemplatesHint: "Brak szablonów. Utwórz szablon w oknie modalnym.",
      rowToolHint: "Rysuj linię na planie, aby utworzyć rząd. Bez szablonu = puste sloty; z szablonem = od razu regały. Później przeciągnij szablon do pustego slotu.",
      saveLayout: "Zapisz układ",
      saving: "Zapisywanie…",
    },
    export: {
      button: "Eksportuj",
      pdf: "PDF",
      csv: "CSV",
      json: "JSON",
      pdfFailed: "Eksport PDF nie powiódł się.",
    },
    rackProperties: {
      title: "Właściwości",
      levelsBins: "Poziomy / Pozycje",
    },
    visuals: {
      toFront: "Na wierzch",
      toBack: "Na dół",
      bringForward: "Do przodu",
      sendBackward: "Do tyłu",
      delete: "Usuń",
      deleteAisle: "Usuń alejkę",
      name: "Nazwa",
      column: "Słupy",
      mezzanine: "Antresole",
      packingStation: "Stanowiska pakowania",
      cart: "Wózki",
      wall: "Ściany",
      door: "Drzwi",
      zone: "Strefa przyjęć/wysyłki",
    },
    templateCreator: {
      name: "Nazwa",
      namePlaceholder: "np. Regał wysokie palety",
      binsPerLevel: "Biny/poziom",
    },
    internalLayout: {
      occupancy: "Zajętość:",
      primary: "Główna",
      reserve: "Rezerwa",
    },
    pdfExport: {
      warehouseLabel: "Magazyn:",
      exportDate: "Data eksportu:",
    },
  },

  labels: {
    categories: {
      warehouse: "Magazyn",
      fleet: "Wózki",
      cart: "Cart",
      basket: "Basket",
      products: "Produkty",
      orders: "Zamówienia",
    },
    templateType: "Template type",
    previewData: "Preview data",
    presets: {
      cartLabel: "Cart label preset",
      basketLabel: "Basket label preset",
    },
    panel: {
      variables: "Zmienne",
      variablesHint: "Kliknij zmienną, aby wstawić ją na środek etykiety.",
      elementProperties: "Właściwości elementu",
      clickToEdit: "Kliknij element, aby edytować (obrót, kolory, tekst pionowy, ikony).",
    },
    designer: {
      labelDesigner: "Projektant etykiet",
      printQueue: "Kolejka druku",
      template: "Szablon:",
      templateName: "Nazwa szablonu",
      widthMm: "Szer. (mm)",
      heightMm: "Wys. (mm)",
      dpi: "DPI (drukarki termiczne: 203–300)",
      conditionalFormatting: "Formatowanie warunkowe",
      conditionalHint: "Kolory etykiet wg typu lokalizacji (np. Rezerwa → czerwone tło)",
      addRule: "+ Reguła",
      addElement: "Dodaj element",
      barcode: "Kod kreskowy",
      dynamicText: "Tekst (powiązanie)",
      staticText: "Tekst stały",
      line: "Linia",
      rect: "Prostokąt",
      statusIcon: "Ikona statusu",
      iconLibrary: "Biblioteka ikon (strzałki)",
      templateLibrary: "Biblioteka szablonów",
      loadSavedTemplate: "Wybierz zapisany szablon",
      saveCurrent: "Zapisz bieżący",
      saveTemplate: "Zapisz szablon",
      removeFromLibrary: "Usuń z biblioteki",
    },
    elementProps: {
      xMm: "X (mm)",
      yMm: "Y (mm)",
      widthMm: "Szer. (mm)",
      heightMm: "Wys. (mm)",
      rotation: "Obrót (°)",
      backgroundColor: "Kolor tła",
      textColor: "Kolor tekstu/obrysu",
      format: "Format",
      dataBinding: "Powiązanie danych",
      showValue: "Pokaż wartość",
      binding: "Powiązanie",
      fontSize: "Rozmiar czcionki",
      align: "Wyrównanie",
      bold: "Pogrubienie",
      verticalText: "Tekst pionowy",
      text: "Tekst",
      icon: "Ikona",
      condition: "Warunek",
      deleteElement: "Usuń element",
    },
    align: {
      left: "Lewo",
      center: "Środek",
      right: "Prawo",
    },
    conditions: {
      reserve: "Rezerwa",
      primary: "Główna",
      bottomLevel: "Dolna półka",
      always: "Zawsze",
    },
    icons: {
      none: "Brak",
      lock: "Kłódka (rezerwa)",
      heavyLoad: "Ciężar (dolna półka)",
      hazard: "Uwaga",
      arrowUp: "Strzałka ↑",
      arrowDown: "Strzałka ↓",
      arrowLeft: "Strzałka ←",
      arrowRight: "Strzałka →",
    },
    iconConditions: {
      always: "Zawsze",
      reserve: "Tylko rezerwa",
      bottomLevel: "Tylko dolna półka",
    },
  },

  common: {
    delete: "Usuń",
    cancel: "Anuluj",
    save: "Zapisz",
    create: "Utwórz",
    edit: "Edytuj",
    close: "Zamknij",
  },
} as const;

export type UIStrings = typeof UI_STRINGS;
