"""Supply Flow — operational phase codes, config defaults, axis compatibility matrix."""

from __future__ import annotations

# Operational lifecycle (canonical). Analysis is background — not a phase.
SUPPLY_FLOW_PHASE_AWIZOWANA = "AWIZOWANA"
SUPPLY_FLOW_PHASE_W_DRODZE = "W_DRODZE"
SUPPLY_FLOW_PHASE_NA_RAMPIE = "NA_RAMPIE"
SUPPLY_FLOW_PHASE_ROZLADUNEK = "ROZLADUNEK"
SUPPLY_FLOW_PHASE_OCZEKUJE_ROZLOKOWANIA = "OCZEKUJE_ROZLOKOWANIA"
SUPPLY_FLOW_PHASE_ROZLOKOWANIE = "ROZLOKOWANIE"
SUPPLY_FLOW_PHASE_ZAKONCZONA = "ZAKONCZONA"

SUPPLY_FLOW_PHASES: tuple[str, ...] = (
    SUPPLY_FLOW_PHASE_AWIZOWANA,
    SUPPLY_FLOW_PHASE_W_DRODZE,
    SUPPLY_FLOW_PHASE_NA_RAMPIE,
    SUPPLY_FLOW_PHASE_ROZLADUNEK,
    SUPPLY_FLOW_PHASE_OCZEKUJE_ROZLOKOWANIA,
    SUPPLY_FLOW_PHASE_ROZLOKOWANIE,
    SUPPLY_FLOW_PHASE_ZAKONCZONA,
)

SUPPLY_FLOW_PHASE_LABELS_PL: dict[str, str] = {
    SUPPLY_FLOW_PHASE_AWIZOWANA: "Awizowana",
    SUPPLY_FLOW_PHASE_W_DRODZE: "W drodze",
    SUPPLY_FLOW_PHASE_NA_RAMPIE: "Na rampie",
    SUPPLY_FLOW_PHASE_ROZLADUNEK: "Rozładunek",
    SUPPLY_FLOW_PHASE_OCZEKUJE_ROZLOKOWANIA: "Oczekuje rozlokowania",
    SUPPLY_FLOW_PHASE_ROZLOKOWANIE: "Rozlokowanie",
    SUPPLY_FLOW_PHASE_ZAKONCZONA: "Zakończona",
}

# Happy-path forward edges (operational axis only).
SUPPLY_FLOW_PHASE_TRANSITIONS: dict[str, frozenset[str]] = {
    SUPPLY_FLOW_PHASE_AWIZOWANA: frozenset(
        {SUPPLY_FLOW_PHASE_W_DRODZE, SUPPLY_FLOW_PHASE_NA_RAMPIE}
    ),
    SUPPLY_FLOW_PHASE_W_DRODZE: frozenset({SUPPLY_FLOW_PHASE_NA_RAMPIE}),
    SUPPLY_FLOW_PHASE_NA_RAMPIE: frozenset({SUPPLY_FLOW_PHASE_ROZLADUNEK}),
    SUPPLY_FLOW_PHASE_ROZLADUNEK: frozenset({SUPPLY_FLOW_PHASE_OCZEKUJE_ROZLOKOWANIA}),
    SUPPLY_FLOW_PHASE_OCZEKUJE_ROZLOKOWANIA: frozenset({SUPPLY_FLOW_PHASE_ROZLOKOWANIE}),
    SUPPLY_FLOW_PHASE_ROZLOKOWANIE: frozenset(
        {SUPPLY_FLOW_PHASE_ZAKONCZONA, SUPPLY_FLOW_PHASE_OCZEKUJE_ROZLOKOWANIA}
    ),
    SUPPLY_FLOW_PHASE_ZAKONCZONA: frozenset(),
}

# Purchase-axis statuses (unchanged DELIVERY_STATUSES).
PURCHASE_STATUS_DRAFT = "draft"
PURCHASE_STATUS_ORDERED = "ordered"
PURCHASE_STATUS_IN_TRANSIT = "in_transit"
PURCHASE_STATUS_RECEIVED = "received"
PURCHASE_STATUS_CANCELLED = "cancelled"

PURCHASE_STATUSES: tuple[str, ...] = (
    PURCHASE_STATUS_DRAFT,
    PURCHASE_STATUS_ORDERED,
    PURCHASE_STATUS_IN_TRANSIT,
    PURCHASE_STATUS_RECEIVED,
    PURCHASE_STATUS_CANCELLED,
)

# Allowed (purchase_status → operational_phase) combinations.
# Two axes — no 1:1 sync; Engine only validates forbidden pairs.
PURCHASE_OPERATIONAL_PHASE_MATRIX: dict[str, frozenset[str]] = {
    PURCHASE_STATUS_DRAFT: frozenset({SUPPLY_FLOW_PHASE_AWIZOWANA}),
    PURCHASE_STATUS_ORDERED: frozenset(
        {SUPPLY_FLOW_PHASE_AWIZOWANA, SUPPLY_FLOW_PHASE_W_DRODZE}
    ),
    PURCHASE_STATUS_IN_TRANSIT: frozenset(
        {
            SUPPLY_FLOW_PHASE_AWIZOWANA,
            SUPPLY_FLOW_PHASE_W_DRODZE,
            SUPPLY_FLOW_PHASE_NA_RAMPIE,
        }
    ),
    PURCHASE_STATUS_RECEIVED: frozenset(
        {
            SUPPLY_FLOW_PHASE_NA_RAMPIE,
            SUPPLY_FLOW_PHASE_ROZLADUNEK,
            SUPPLY_FLOW_PHASE_OCZEKUJE_ROZLOKOWANIA,
            SUPPLY_FLOW_PHASE_ROZLOKOWANIE,
            SUPPLY_FLOW_PHASE_ZAKONCZONA,
        }
    ),
    # Cancelled: allow any SF phase already possible on the path (no auto-overwrite).
    PURCHASE_STATUS_CANCELLED: frozenset(SUPPLY_FLOW_PHASES),
}

# Optimization goals (warehouse Supply Flow config — not plan fields).
GOAL_MAX_SHIPPED_ORDERS = "MAX_SHIPPED_ORDERS"
GOAL_MIN_OPERATOR_TRAVEL = "MIN_OPERATOR_TRAVEL"
GOAL_MIN_CROSS_DOCK_OCCUPANCY = "MIN_CROSS_DOCK_OCCUPANCY"
GOAL_CLEAR_RAMPS = "CLEAR_RAMPS"
GOAL_MAX_THROUGHPUT = "MAX_THROUGHPUT"

SUPPLY_FLOW_OPTIMIZATION_GOALS: tuple[str, ...] = (
    GOAL_MAX_SHIPPED_ORDERS,
    GOAL_MIN_OPERATOR_TRAVEL,
    GOAL_MIN_CROSS_DOCK_OCCUPANCY,
    GOAL_CLEAR_RAMPS,
    GOAL_MAX_THROUGHPUT,
)

DEFAULT_OPTIMIZATION_GOAL = GOAL_MAX_SHIPPED_ORDERS
DEFAULT_PLANNING_HORIZON_HOURS = 24

# Recompute trigger codes (hooks only in stage 1).
RECOMPUTE_NEW_ORDER = "NEW_ORDER"
RECOMPUTE_ORDER_CANCELLED = "ORDER_CANCELLED"
RECOMPUTE_NEW_DELIVERY = "NEW_DELIVERY"
RECOMPUTE_PHASE_CHANGED = "PHASE_CHANGED"
RECOMPUTE_UNLOAD_FINISHED = "UNLOAD_FINISHED"
RECOMPUTE_PUTAWAY_FINISHED = "PUTAWAY_FINISHED"
RECOMPUTE_CAPACITY_CHANGED = "CAPACITY_CHANGED"
RECOMPUTE_CROSS_DOCK_FREED = "CROSS_DOCK_FREED"
RECOMPUTE_OPERATOR_SHIFT_ENDED = "OPERATOR_SHIFT_ENDED"
RECOMPUTE_RECOVERY_CHANGED = "RECOVERY_CHANGED"
RECOMPUTE_MANUAL = "MANUAL"
RECOMPUTE_ETA_CHANGED = "ETA_CHANGED"
RECOMPUTE_CONFIG_CHANGED = "CONFIG_CHANGED"

SUPPLY_FLOW_RECOMPUTE_TRIGGERS: tuple[str, ...] = (
    RECOMPUTE_NEW_ORDER,
    RECOMPUTE_ORDER_CANCELLED,
    RECOMPUTE_NEW_DELIVERY,
    RECOMPUTE_PHASE_CHANGED,
    RECOMPUTE_UNLOAD_FINISHED,
    RECOMPUTE_PUTAWAY_FINISHED,
    RECOMPUTE_CAPACITY_CHANGED,
    RECOMPUTE_CROSS_DOCK_FREED,
    RECOMPUTE_OPERATOR_SHIFT_ENDED,
    RECOMPUTE_RECOVERY_CHANGED,
    RECOMPUTE_MANUAL,
    RECOMPUTE_ETA_CHANGED,
    RECOMPUTE_CONFIG_CHANGED,
)

PHASE_HISTORY_SOURCE_SYSTEM = "system"
PHASE_HISTORY_SOURCE_API = "api"
PHASE_HISTORY_SOURCE_RECEIVING = "receiving"
PHASE_HISTORY_SOURCE_PUTAWAY = "putaway"
PHASE_HISTORY_SOURCE_MANUAL = "manual"
