"""Operator runtime context types."""

CONTEXT_PICKING = "PICKING"
CONTEXT_PACKING = "PACKING"
CONTEXT_REPLENISHMENT = "REPLENISHMENT"
CONTEXT_DIRECT_SALE = "DIRECT_SALE"
CONTEXT_PICKUP = "PICKUP"
CONTEXT_RETURNS = "RETURNS"
CONTEXT_AUDIT = "AUDIT"

CONTEXT_TYPES = (
    CONTEXT_PICKING,
    CONTEXT_PACKING,
    CONTEXT_REPLENISHMENT,
    CONTEXT_DIRECT_SALE,
    CONTEXT_PICKUP,
    CONTEXT_RETURNS,
    CONTEXT_AUDIT,
)
